#+title: zed config
#+auto_tangle:t
#+startup: content indent

* start/enabler
#+begin_src nix :tangle default.nix
{pkgs, ... }:
{
  programs.zed-editor = {
    enable = true;
#+end_src

Whether to enable Zed, the high performance, multiplayer code editor from the creators of Atom and Tree-sitter.

* extraPackages
Extra packages available to Zed.

#+begin_src nix :tangle default.nix
    # package = pkgs.zed-editor;
    extraPackages = [
      pkgs.nixd
      # pkgs.nil
    ];
#+end_src

* Extensions
A list of the extensions Zed should install on startup. Use the name of a repository in the extension list.

#+begin_src nix :tangle no
extensions = [ "qml" "nix" "python"]; # make
#+end_src

* userSettings

Configuration written to Zed's settings.json

You can find the default settings for your current Zed by running =zed: open default settings= from the command palette.

** start
#+begin_src nix :tangle default.nix
    userSettings = {
#+end_src
** misc
#+begin_src nix :tangle no
  # features = {
  #   edit_prediction_provider = "copilot";
  # };
  relative_line_numbers = "enabled";
  auto_install_extensions = {
    nix = true;
    python = true;
  };
  hour_format = "hour24"; # The format to use for displaying hours in the journal. hour12::
  remove_trailing_whitespace_on_save = true;
  soft_wrap = "bounded"; # def: none, # edditor_width, prefer_line_length, bounded
  show_wrap_guides = false; # true::
  preferred_line_length = 80; #80:;
  auto_update = false;
  confirm_quit = true;
#+end_src

** ui/ux
#+begin_src nix :tangle no
vim_mode = true;
tab_size = 2; # 4:: how many columns a tab should occupy
hard_tabs = false; # tabs or spaces, false for tabs #TODO:test
# autoscroll_on_clicks = true;
hover_popover_enabled = true;
show_whitespaces = "selection"; # selection, boundary, all , none
current_line_highlight = "line"; # line, none, all, gutter
#+end_src

** fonts
#+begin_src nix :tangle no
ui_font_size = 16;
ui_font_features = {
  calt = true; #disable ligatures
  # "cv01" = 7;
};
ui_font_fallbacks = "Symbol Nerd Font";
ui_font_weight = 450; # 400::

buffer_font_size = 15;
buffer_font_family = "JetBrains Mono";
buffer_font_weight = 400; # default 400, 100-900
buffer_line_height = "comfortable";
#+end_src

** autosave

#+begin_src nix :tangle no
autosave = {
  after_delay = {
    milliseconds = 1000;
  };
};
#+end_src

#+begin_src nix :tangle no
  autosave = { "after_delay" = {"milliseconds" = 500;}; };
#+end_src

+ on_focus_change
+ off
+ on_window_change
+ after_delay

** assistant (Ai)
#+begin_src nix :tangle no
# assistant = {
#     enabled = false;
#     version = "2";
#     default_open_ai_model = null;
#     default_model = {
#         provider = "zed.dev";
#         model = "claude-3-5-sonnet-latest";
#     };
# };
#+end_src

** search
#+begin_src nix :tangle no
search = {
  whole_word = false;
  case_sensitive = false;
  include_ignored = false;
  regex = false;
};
#+end_src

** editors tab bar
#+begin_src nix :tangle no
"tab_bar" = {
  "show" = true;
  "show_nav_history_buttons" = true;
  "show_tab_bar_buttons" = true;
};
#+end_src

** tabs
Configuration for the editor tabs.

#+begin_src nix :tangle no
tabs = {
  close_position = "right";
  file_icons = true;
  git_status = false;
  activate_on_close = "history"; # history::, neighbour
  show_close_button = false;
  # show_diagnostics = "off"
};
#+end_src
** toolbar
#+begin_src nix :tangle no
toolbar = {
  breadcrumbs = true;
  quick_actions = true;
};
#+end_src
** preview_tabs
#+begin_src nix :tangle no
# preview_tabs = {
#   enabled = true;
#   enable_preview_from_file_finder = true;
#   enable_preview_from_code_navigation = true;
# };
#+end_src

** scrollbar
#+begin_src nix :tangle no
scrollbar = {
  show = "never"; # auto, never, always, system (match system config)
  cursors = true; # show cursor position on the scrollbar
  git_diff = true; # git diff indicators
  search_results = true; # search results
  selected_symbol = true;
  selected_text = true; # selected text occurrences
  diagnostics = "all"; # all::, error, warning, information, none,
};
#+end_src

** cursor
#+begin_src nix :tangle no
cursor_shape = "block"; # block, bar::, underline, hollow
#+end_src
** mouse
#+begin_src nix :tangle no
hide_mouse = "on_typing_and_movement"; # on_typing, never, on_typing_and_movement::
#+end_src

** language server
#+begin_src nix :tangle no
enable_language_server = true; # on default
format_on_save = "off";
#+end_src

** project panel
#+begin_src nix :tangle no
project_panel = {
  indent_guides = {
    show = "always"; # never, always
  };
};
#+end_src

** languages - major modes
#+begin_src nix :tangle no
languages = {
  Python = {
    tab_size = 4;
    #indent_guides.enabled = true;
    # format_on_save = false;
    soft_wrap = "preferred_line_length";
    # formatter = {language_server.name = ruff ;};
    # external =  {
    #   command = "black";
    #   arguments = ["--stdin-filename" "{buffer_path}" "-"];
    # };
    language_servers = [
      "basedpyright"
      # "!ty"
      "..."                     # otherwise use default
    ];
  };
    # "ruff": {
    #   "initialization_options": {
    #     "settings": {
    #       "exclude": ["*"]
    #     }
    #   }
    # }
  nix = {
    tab_size = 2;
    language_servers = [
      "nil"
      "nixd"
      "..."
    ];
    prettier = {
      allowed = true;
    };
  };
};
#+end_src

** lsp
Description: Configuration for language servers.
Setting: lsp
Default: null

Options:
The following settings can be overridden for specific language servers:
    + initialization_options
    + settings

Some options are passed via =initialization_options= to the language server.
These are for options which must be specified at language server startup and when changed will require restarting the language server.

*** debounce
#+begin_src nix :tangle no
# lsp_highlight_debounce = 75; # 75::
#+end_src

*** general lsp
#+begin_src nix :tangle no

lsp = {
  #     rust-analyzer = {

  #         binary = {
  #             #                        path = lib.getExe pkgs.rust-analyzer;
  #             path_lookup = true;
  #         };
  #     };
  # nil = {
  #    initialization_options = {# these initialization_options are merged into zed's defaults
  #      formatting = {
  #        command = ["nixfmt"];
  #      };
  #    settings = {
  #      diagnostic = {
  #        ignored = ["unused_binding"];
  #      };
  #    };
  #    };
  #  };

    # Python
    basedpyright = {
      diagnosticMode = "workspace";
      inlayHints = {
        callArgumentNames = false;
      };
    };

    qml = {
      binary = {
        arguments = ["-E" "additional-args"];
      };
      tab_size = 2;
    };
  # nixd = {
  #   settings = {
  #     diagnostic = {
  #       suppress = ["sema-extra-with"];
  #     };
  #   };
  # };

  # nix = {
  #     binary = {
  #         path_lookup = true;
  #     };
  # };
};
#+end_src

** formatter
#+begin_src nix :tangle no
# formatter = "prettier"; # language_server , auto, prettier, external
formatter = {
  external = {
    command = "prettier";
    arguments = ["--stdin-filepath" "{buffer_path}"];
};
#+end_src

https://zed.dev/docs/configuring-zed#formatter
** diagnostics
#+begin_src nix :tangle no
diagnostics = {
  "include_warnings" = true;
  "inline" = {
    enabled = true;
    "update_debounce_ms" = 150;
    padding = 4; # padding between the end of the source line and the start of the diagnostic.
    "min_column" = 80;
  };
  "update_with_cursor" = false;
  "primary_only" = false;
  "use_rendered" = false;
};
#+end_src
** git
#+begin_src nix :tangle no
git = {
  "git_gutter" = "tracked_files"; # tracked_files::, hide
  "gutter_debounce" = 100; # in ms
  "inline_blame" = {
    "enabled" = true;
    "show_commit_summary" = true;
  };
  "hunk_style" = "staged_hollow"; # staged_hollow::, unstaged_hollow
};
#+end_src

** vim
#+begin_src nix :tangle no
vim = {
  toggle_relative_line_numbers = true;
  use_system_clipboard = "always";
  highlight_on_yank_durations = 200;
  # custom_digraphs = {}; #TODO: findout what this does
};
#+end_src

** base keymap
Description: Base key bindings scheme. Base keymaps can be overridden with user keymaps.

#+begin_src nix :tangle no
base_keymap = "JetBrains"; # VSCode, Atom,
#+end_src

** theme
Each theme is written to $XDG_CONFIG_HOME/zed/themes/theme-name.json where the name of each attribute is the theme-name

See https://zed.dev/docs/extensions/themes for the structure of a Zed theme.

Run the =theme selector: toggle= action in the command palette to see a current list of valid themes names.

#+begin_src nix :tangle no
theme = {
  mode = "system"; # system, dark, light
  light = "Rosé Pine Dawn";
  #dark = "One Dark";
  #dark = "Rosé Pine";
  dark = "Gruvbox Dark Soft";
};
#+end_src

** indent_guides
#+begin_src nix :tangle no
indent_guides = {
  enabled = false;
  coloring = "indent_aware"; # disabled, indent_aware, "fixed"
  line_width = 1; # 1-10 in pixels
  active_line_width = 1; # 1-10
  background_coloring = "indent_aware"; # indent_aware, disabled
};
#+end_src
** inlay hints
#+begin_src nix :tangle no
inlay_hints = {
  enabled = false;
  show_type_hints = true;
  show_parameter_hints = true;
  show_other_hints = true;
  show_background = false;
  edit_debounce_ms = 700;
  scroll_debounce_ms = 50;
  toggle_on_modifiers_press = null;
};
#+end_src

** centered layout
#+begin_src nix :tangle no
centered_layout = {
  left_padding = 0.2;
  right_padding = 0.2;
};
#+end_src

** telemetry
#+begin_src nix :tangle no
telemetry = {
  diagnostics = false;
  metrics = false;
};
#+end_src
** terminal
#+begin_src nix :tangle no
terminal = {
  alternate_scroll = "off";
  blinking = "off";
  copy_on_select = true;
  dock = "bottom";
  # detect_venv = {
  #     on = {
  #         directories = [".env" "env" ".venv" "venv"];
  #         activate_script = "default";
  #     };
  # };
  # env = {
  #     TERM = "kitty";
  # };
  #font_family = "FiraCode Nerd Font";
  font_family = "Zed Plex Mono";
  #font_features = null;
  font_size = 15;
  line_height = "comfortable";
  option_as_meta = false;
  button = false;
  shell = "system";
  #{
  #                    program = "zsh";
  #};
  toolbar = {
    title = true;
  };
  working_directory = "current_project_directory";
  cursor_blink = false;
  cursor_shape = "underline"; # block, bar, hollow,underline
};
#+end_src

** direnv
#+begin_src nix :tangle no
## tell zed to use direnv and direnv can use a flake.nix enviroment.
# load_direnv = "shell_hook";
#+end_src
** ender
#+begin_src nix :tangle default.nix
    };
#+end_src
* userKeymaps
Configuration written to Zed's keymap.json
#+begin_src nix :tangle no
userKeymaps = [
  {
    context = "Workspace";
    bindings = {
      ctrl-shift-t = "workspace::NewTerminal";
    };
  };
];
#+end_src
* Ender
#+begin_src nix :tangle default.nix
  }; # end of programs.zed
}
#+end_src
