#+title: Themes + Dconf
#+auto_tangle: t
#+startup: content indent

* start / hyprland condition
#+begin_src nix :tangle default.nix
{pkgs, osConfig, lib, config, ...}:

# let
#   gruvboxplus = import ../home/gruvbox-plus.nix { inherit pkgs;};
# in
# lib.mkIf osConfig.services.desktopManager.plasma6.enable {
lib.mkIf osConfig.programs.hyprland.enable {
#+end_src

* home
#+begin_src nix :tangle default.nix
home.pointerCursor = {
  enable = true; # false::
  gtk.enable = true; # waybar, gtk apps
  dotIcons.enable = true;
  hyprcursor = {
    size = 24; # 32::
    enable = true;
  };
  x11 = {
    enable = true;
    # defaultCursor = "X_cursor"; # letf_ptr::
  };
  # name = "Bibata-Modern-Ice"; package = pkgs.bibata-cursors;
  # name = "bibata-cursors"; package = pkgs.bibata-cursors;
  name = "GoogleDot-Black";  package = pkgs.google-cursor; # android-studio
  size = if osConfig.networking.hostName == "carthage" then 24 else if osConfig.networking.hostName == "tangier" then 20 else 18;
};
#+end_src

name: The cursor name within the package.

~error~: The option `home-manager.users.malu.home.pointerCursor.package' was accessed but has no value defined. Try setting the option.

* gtk applications
** start
#+begin_src nix :tangle default.nix
gtk = {
  enable = true;
  #font = {
  #name = "DaddyTimeMono Nerd Font";
  #size = 12;
  #};
#+end_src

** cursor theme (waybar, gtk apps)
#+begin_src nix :tangle default.nix
cursorTheme = {
  name = "Bibata-Modern-Ice"; package = pkgs.bibata-cursors;
  # name = "google-cursor"; package = pkgs.google-cursor;
  size = if osConfig.networking.hostName == "carthage" then 24 else if osConfig.networking.hostName == "tangier" then 20 else 18;
};
#+end_src

** gtk theme
#+begin_src nix :tangle default.nix
theme = {
  name = "Nightfox-Dark";  package = pkgs.nightfox-gtk-theme;
  # name = "breeze-gtk";  package = pkgs.kdePackages.breeze-gtk;
  # name = "Yaru-Dark";  package = pkgs.yaru-theme;
  # name = "tokyonight-gtk-theme"; package = pkgs.Tokyonight-Moon;
};
#+end_src

** iconTheme
#+begin_src nix :tangle default.nix
iconTheme = {
  name = "Colloid-Catppuccin"; package = pkgs.colloid-icon-theme.override {schemeVariants = ["catppuccin"];};
  # name = "kora"; package = pkgs.kora-icon-theme;
  # name = "WhiteSur"; package = pkgs.whitesur-icon-theme;
  # name = "candy-icons"; package = pkgs.candy-icons;
  # name = "Papirus-Dark"; package = pkgs.papirus-icon-theme;

  # name = "gruvbox-plus-icons";  package = pkgs.gruvbox-plus-icons;
  # name = "Windows10-icons"; package = pkgs.windows10-icons;
};
#+end_src

** gtk2, gtk3, gtk4 extraConfig
#+begin_src nix :tangle default.nix
gtk2 = {
  # extraConfig = ''
  #       "gtk-can-change-accels" = "1"
  #     ''; #TODO see importance
  configLocation = "${config.xdg.configHome}/gtk-2.0/gtkrc";
};

gtk3 = {
  extraConfig = {
    gtk-application-prefer-dark-theme = 1;
  };
  # bookmarks = [ #FIXME error
  #   "file://home/malu/org"
  # ];
};

gtk4 = {
  # extraCss = '''';
  extraConfig = {
    #     #gtk-theme-name = ''Nightfox:Dark''; #eg nautilus
    #     gtk-theme-name = "Nightfox-Dark"; #eg nautilus
    #     gtk-cursor-blink = false;
    # gtk-recent-files-limit = 20;
    gtk-application-prefer-dark-theme = 1;
  };
  #   # extraCss = #gtk-4.0/gtk.css
  #   #   ''
  #   # '';
};
#+end_src

** end
#+begin_src nix :tangle default.nix
};
#+end_src

* qt
#+begin_src nix :tangle default.nix
qt = {
  enable = true;
  platformTheme.name = "kde6";   # kde6(stable)
  style.name = "breeze"; #"adwaita-dark";
};
#+end_src

** =qt.style.name=
Style to use for =Qt5/Qt6= applications. Case-insensitive.

Some examples are:
- =adwaita,= adwaita-dark, adwaita-highcontrast, adwaita-highcontrastinverse : Use the Adwaita style from [[github:FedoraQt/adwaita-qt][adwaita-qt]]
- =breeze= : Use the Breeze style from =breeze=
- bb10bright, bb10dark, cde, cleanlooks, gtk2, motif, plastique : Use styles from =qtstyleplugins=
- =kvantum= : Use styles from =kvantum.=

** =qt.platformTheme=
Selects the platform theme to use for Qt applications.
The options are:
- =gnome=: Use GNOME theme with qgnomeplatform
- =gtk2=: Use GTK theme with qtstyleplugins
- =kde=: Use Qt settings from Plasma.
- =lxqt=: Use LXQt style set using the lxqt-config-appearance application.
- =qt5ct=: Use Qt style set using the qt5ct and qt6ct applications.

** =qt.style=
Selects the style to use for Qt applications.
The options are:
- =adwaita=, adwaita-dark, adwaita-highcontrast, adawaita-highcontrastinverse: Use Adwaita Qt style with adwaita
- =breeze=: Use the Breeze style from breeze
- bb10bright, bb10dark, cleanlooks, gtk2, motif, plastique: Use styles from qtstyleplugins
- =kvantum=: Use styles from kvantum.

  =NOTE= platformTheme: gnome deprecated use 'adwaita'
* Dconf
#+begin_src nix :tangle no
 dconf.settings = {
   "/org/gnome/desktop/interface" = {
     # gtk-theme = "Nightfox-Dark";
     gtk-theme = "nightfox-gtk-theme";

   };
 };
#+end_src
Jun 07 16:23:49 carthage hm-activate-malu[19264]: Activating dconfSettings
Jun 07 16:23:49 carthage hm-activate-malu[19682]: error: [/org/gnome/desktop/interface]: gtk-theme: invalid path: dconf key must not contain two consecutive slashes
* end
#+begin_src nix :tangle default.nix
}
#+end_src
