#+title: maluware flake
#+auto_tangle: t
#+startup: content indent

* inputs
** description, inputs start
#+begin_src nix :tangle flake.nix
{
  description = "Kenyan Tinkerer makes a flake -- 🫥";
  inputs = {
#+end_src

** nixpkgs
#+begin_src nix :tangle flake.nix
    # nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
    # nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
#+end_src

nixos-unstable-small exist...smaller, update faster but require more to be built from source

https://nixos.wiki/wiki/Nix_channels
** disko
#+begin_src nix :tangle flake.nix
  disko.url = "github:nix-community/disko/latest";
  disko.inputs.nixpkgs.follows = "nixpkgs";
#+end_src

** yazi
#+begin_src nix :tangle flake.nix
    yazi.url = "github:sxyazi/yazi";
#+end_src

** quickshell 🖥
#+begin_src nix :tangle flake.nix
    quickshell = {
      # add ?ref=<tag> to track a tag
      url = "git+https://git.outfoxxed.me/outfoxxed/quickshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };
#+end_src
** nix-qml-support
#+begin_src nix :tangle flake.nix
    nix-qml = {
      url = "git+https://git.outfoxxed.me/outfoxxed/nix-qml-support";
      inputs.nixpkgs.follows = "nixpkgs";
    };
#+end_src
** home-manager
#+begin_src nix :tangle flake.nix
    # home-manager = {
    #   url = "github:nix-community/home-manager/release-25.05";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
#+end_src
** plasma-manager
#+begin_src nix :tangle no
    plasma-manager = {
      url = "github:nix-community/plasma-manager";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
#+end_src
** winapps
#+begin_src nix :tangle no
    winapps = {
      url = "github:winapps-org/winapps";
      inputs.nixpkgs.follows = "nixpkgs";
    };
#+end_src

** hyprland ecos
#+begin_src nix :tangle flake.nix
    # hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1";

    # hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1&ref={version}";

    hyprland.url = "github:hyprwm/Hyprland"; # with cachix

    # hyprland-plugins.url = "github:hyprwm/hyprland-plugins";
    # hyprland-plugins.inputs.hyprland.follows = "hyprland";

    hyprlock = {
      url = "github:hyprwm/hyprlock";
      inputs = {
        hyprgraphics.follows = "hyprland/hyprgraphics";
        hyprlang.follows = "hyprland/hyprlang";
        hyprutils.follows = "hyprland/hyprutils";
        nixpkgs.follows = "hyprland/nixpkgs";
        systems.follows = "hyprland/systems";
      };
    };

    # hyprsunset = { # TODO: test if needed
    #   url = "github:hyprwm/hyprsunset";
    #   inputs = {
    #     hyprgraphics.follows = "hyprland/hyprgraphics";
    #     hyprlang.follows = "hyprland/hyprlang";
    #     hyprutils.follows = "hyprland/hyprutils";
    #     nixpkgs.follows = "hyprland/nixpkgs";
    #     systems.follows = "hyprland/systems";
    #   };
    # };

    hyprpaper = {
      url = "github:hyprwm/hyprpaper";
      inputs = {
        hyprgraphics.follows = "hyprland/hyprgraphics";
        hyprlang.follows = "hyprland/hyprlang";
        hyprutils.follows = "hyprland/hyprutils";
        nixpkgs.follows = "hyprland/nixpkgs";
        systems.follows = "hyprland/systems";
      };
    };

    # hyprland-plugins = {
    #     url = "github:hyprwm/hyprland-plugins";
    #     inputs.hyprland.follows = "hyprland";
    # };

    # hyprland-easymotion = {
    #   url = "github:zakk4223/hyprland-easymotion";
    #   inputs.hyprland.follows = "hyprland";
    # };

    # Hyprspace = {
    #   url = "github:KZDKM/Hyprspace";

    #   # Hyprspace uses latest Hyprland. We declare this to keep them in sync.
    #   inputs.hyprland.follows = "hyprland";
    # };
  #+end_src

** nyaa
#+begin_src nix :tangle flake.nix
    nyaa = {
      url = "github:Beastwick18/nyaa";
      inputs.nixpkgs.follows = "nixpkgs";
    };
#+end_src
** end inputs
#+begin_src nix :tangle flake.nix
  };
#+end_src

-----

* outputs
#+begin_src nix :tangle flake.nix
  outputs = inputs@{nixpkgs, disko, ...}: # Note the use of `self` which allows reusing flake's outputs in itself.
#+end_src
** let..in
*** start
#+begin_src nix :tangle flake.nix
let
  system = "x86_64-linux"; # TODO system = builtins.currentSystem;?? find reason it doesn't work

  config = {
#+end_src

*** Allow Unfree
#+begin_src nix :tangle flake.nix
    allowUnfreePredicate = pkg: builtins.elem (nixpkgs.lib.getName pkg) [
      "aspell-dict-en-science"
      "discord"
      "evafast"
      "google-chrome"
      "rar"
      "spotify"
      "steam"
      "steam-unwrapped"
      "unrar"
      "ventoy"
      "xow_dongle-firmware"
      "youtube-upnext"
      "davinci-resolve"
      "wpsoffice"
    ];
#+end_src

*** Permit Insecure
#+begin_src nix :tangle flake.nix
    permittedInsecurePackages = [
      "ventoy-1.1.10"
      "libsoup-2.74.3"
      "libxml2-2.13.8" # for cisco?
      "qtwebengine-5.15.19" 
      "beekeeper-studio-5.5.3"
    ];
#+end_src

*** pkgs | home
#+begin_src nix :tangle flake.nix
};
 home = inputs.home-manager;

 # pkgs = nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system};#FIXME better way to do this...+ inherit config
 pkgs = import nixpkgs {
   inherit  system;
   inherit config;
 };
#+end_src

*** end of in
#+begin_src nix :tangle flake.nix
in
{
  # This will make the package available as a flake output under 'packages'
  # packages.${pkgs.stdenv.hostPlatform.system}.my-neovim = customNeovim.neovim;
#+end_src

** Nix configurations
*** CARTHAGE
**** init | specialArgs
#+begin_src nix :tangle flake.nix
nixosConfigurations = {
  carthage = nixpkgs.lib.nixosSystem {
    inherit system;
    specialArgs = { inherit inputs system; };
#+end_src

**** Modules
***** start | nix import
#+begin_src nix :tangle flake.nix
modules = [
  ./hosts/carthage
#+end_src

***** Some systemPackage modules | winapps | rebuild-ng
#+begin_src nix :tangle no
{environment.systemPackages = [
   # pkgs.nixos-rebuild-ng #  alternatively to replace old rebuild: system.rebuild.enableNg
   inputs.winapps.packages."${pkgs.stdenv.hostPlatform.system}".winapps
   inputs.winapps.packages."${pkgs.stdenv.hostPlatform.system}".winapps-launcher # optional
 ];
}
#+end_src

***** plasma-manger
#+begin_src nix :tangle no
  inputs.plasma-manager.homeManagerModules.plasma-manager
#+end_src
***** disko
#+begin_src nix :tangle flake.nix
disko.nixosModules.disko
./hosts/common/disko.nix
#+end_src

***** Home-manager
****** As Module 🐐
#+begin_src nix :tangle flake.nix
  home.nixosModules.home-manager {
    home-manager = {
      verbose = true;
      backupFileExtension = "home_bak";
      useGlobalPkgs = true; # if true dont use private instance of pkgs which is the default
      useUserPackages = false; # if false ... uses nix-profile for home apps
      extraSpecialArgs = { inherit inputs pkgs system; };
      users.malu = import ./modules/home/home.nix;
    };
  }
#+end_src

******* Extras
extraSpecialArgs: By default packages will be installed to $HOME/.nix-profile but they can be installed to /etc/profiles if true

By default, Home Manager uses a private pkgs instance that is configured via the home-manager.users.<name>.nixpkgs options.
  To instead use the global pkgs that is configured via the system level nixpkgs options, set userGlobalPkgs = true
  This saves an extra Nixpkgs evaluation, adds consistency, and removes the dependency on NIX_PATH, which is otherwise used for importing Nixpkgs.

To troubleshoot home manager:
#+begin_src sh
systemctl status "home-manager-$USER.service"
#+end_src

=To automatically create flake in /etc/nixos=
#+begin_src sh
nix flake new /etc/nixos -t github:nix-community/home-manager#nixos
#+end_src

******** StandAlone
This will generate a flake.nix and a home.nix file in ~/.config/home-manager, creating the directory if it does not exist:
=Unstable=
  #+begin_src shell
  nix run home-manager/master -- init --switch
  #+end_src

=Stable=
  #+begin_src shell
  nix run home-manager/release-25.05 -- init --switch
  #+end_src

to override default config directory:
  #+begin_src sh
nix run home-manager/$branch -- init --switch ~/hmconf
# And after the initial activation.
home-manager switch --flake ~/hmconf
  #+end_src

If you omit the --switch option then the activation will not happen. This is useful if you want to inspect and edit the configuration before activating it.

After the initial activation has completed successfully then building and activating your flake-based configuration is as simple as:
#+begin_src sh
home-manager switch
#+end_src

The flake inputs are not automatically updated by Home Manager. You need to use the standard =nix flake update= command for that.

If you only want to update a single flake input, then the command =nix flake lock --update-input <input>= can be used.

You can also pass flake-related options such as =--recreate-lock-file= or =--update-input <input>= to home-manager when building or switching, and these options will be forwarded to nix build.
See the NixOS Wiki page for details.
******** Module AutoImport
Home manager imports all modules from the /modules/program /modules/services:
+ all nix files
+ all subdirectories (with default.nix)
+ _files: excluded from autoImport
***** Ender
#+begin_src nix :tangle flake.nix
];  # modules
 };  # carthage
#+end_src

*** tangier
#+begin_src nix :tangle flake.nix
tangier = nixpkgs.lib.nixosSystem {
  inherit system;
  specialArgs = { inherit inputs system; };
  modules = [
    ./hosts/tangier
    home.nixosModules.home-manager {
      home-manager = {
        verbose = true;
        backupFileExtension = "home_backup";
        users.malu = import ./modules/home/home.nix;
        useGlobalPkgs = true; # dont use private instance of pkgs which is the default
        useUserPackages = false; # if false:: ... uses nix-profile for home apps
        extraSpecialArgs = { inherit pkgs inputs system; };
      };
    }
  ];
};
#+end_src

*** End of nix configurations
#+begin_src nix :tangle flake.nix
}; #End of NixConfigurations
#+end_src

** devshell - nix develop
*** teal environment / python
#+begin_src nix :tangle flake.nix
devShells.${pkgs.stdenv.hostPlatform.system}.default = pkgs.mkShell {
  buildInputs = with pkgs; [
    # numpy
    (pkgs.python3.withPackages (python-pkgs: with python-pkgs; [
      # pip
      # numpy
      adblock
    ]))
  ];

  shellHook = ''
      echo "$USER:: welcome to your dev env lul 🧊"
    '';

  # packages = [
  #inputs.python-nixpkgs.legacyPackages.${pkgs.stdenv.hostPlatform.system}.python313
  #     (pkgs.python3.withPackages (python-pkgs: with python-pkgs; [
  #     pip
  #     ]))
  # ];
  # env.LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
  #   pkgs.stdenv.cc.cc.lib
  #   pkgs.libz
  # ];
  # shellHook = ''
  #     if [ ! -d .venv ]; then
  #         python -m venv .venv
  #     fi
  #     source .venv/bin/activate
  # '';
};
#+end_src

*** QML outfoxx
#+begin_src nix :tangle no
packages = [
  
];
#+end_src

*** vimjoyer new
**** non nix
then use nix-shell
#+begin_src nix :tangle no
  packages = [
    pkgs.python3
  ];

  env.LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
    pkgs.libz
    pkgs.stdenv.cc.cc.lib
  ];
  #+end_src
  #+begin_src nix :tangle no
  pkgs.mkShell = {
      packages = [
      (pkgs.python3.withPackages(p: with p[
          pandas
          requests
      ]))
      ];
  }
#+end_src
**** nix way - bundle packages in python instance
Then use nix-shell
pypkgs / p
*** guy
#+begin_src nix :tangle no
    devShells.${pkgs.stdenv.hostPlatform.system} = {
      simple = pkgs.mkShell {
        packages = [ pkgs.hello ];
        shellHook = ''
          ${pkgs.hello}/bin/hello
        '';
      };

      default = pkgs.mkShell {
        packages = [
          # newer versions of redis are not packaged in
          # nixpkgs, so we're using valkey, an open-source
          # fork of redis maintained by the Linux Foundation
          # pkgs.valkey

          # pkgs.nodejs_22
          # pkgs.nodePackages.pnpm

          # the friendly interactive shell!
          pkgs.fish
        ];

        # shellHook = ''
          # ${pkgs.valkey}/bin/valkey-server ${valkeyConf} &
          # exec fish
        # '';
      };
    };
#+end_src

*** shellHook
Optional: Set up a Python virtual environment automatically
** end of out outputs
* EOF
#+begin_src nix :tangle flake.nix
  };   # end of outputs
}    # EOF
#+end_src
