#+title: Docs
#+startup: content indent

* hyprctl
|-----------+------------------------------------------------------------------------------------------------------------------+---------------------------|
| command   | does                                                                                                             | comment                   |
|-----------+------------------------------------------------------------------------------------------------------------------+---------------------------|
| =dispatch=  | Issue a dispatch to call a keybind dispatcher with an argument.                                                  | ~ok~ on success ERR on fail |
| =keyword=   | issue a keyword to call a config keyword dynamically.                                                            |                           |
| =kill=      | go into kill mode - click an app to close it                                                                     |                           |
| =setcursor= | Sets the cursor theme and reloads the cursor manager. Will set the theme for everything except GTK, because GTK. |                           |
| =notify=    | Sends a notification using the built-in Hyprland notification system.                                            |                           |
| =info=    |                                                                                                                  |                           |
| =batch=     |                                                                                                                  |                           |
| =flags=     |                                                                                                                  |                           |
|-----------+------------------------------------------------------------------------------------------------------------------+---------------------------|

** examples
source:[[https://wiki.hyprland.org/Configuring/Using-hyprctl/]]
*** dispatch
To pass an argument starting with - or --, such as command line options to exec programs, pass -- as an option. This will disable any subsequent parsing of options by hyprctl.

#+begin_src shell
hyprctl dispatch exec kitty

hyprctl dispatch -- exec kitty --single-instance

hyprctl dispatch pseudo x
#+end_src
*** keyword
#+begin_src sh
hyprctl keyword bind SUPER,O,pseudo

hyprctl keyword general:border_size 10

hyprctl keyword monitor DP-3,1920x1080@144,0x0,1
#+end_src
*** kill
go into kill mode - click an app to close it
*** setcursor
Please note that since 0.37.0, this only accepts hyprcursor themes. For =legacy xcursor= themes, use the =XCURSOR_THEME= and =XCURSOR_SIZE= env vars.

params: theme and size eg:
#+begin_src shell
hyprctl setcursor Bibata-Modern-Classic 24
#+end_src
*** notify
Sends a notification using the built-in Hyprland notification system.

hyprctl notify [ICON] [TIME_MS] [COLOR] [MESSAGE]
eg:
#+begin_src sh
hyprctl notify -1 10000 "rgb(ff1ea3)" "Hello everyone!"
#+end_src

Icon of =-1= means =“No icon”=

Color of =0= means =“Default color for icon”=

Icon list:
#+begin_src sh
WARNING = 0
INFO = 1
HINT = 2
ERROR = 3
CONFUSED = 4
OK = 5
#+end_src

Optionally, you can specify a font size of the notification like so:
#+begin_src sh
hyprctl notify -1 10000 "rgb(ff0000)" "fontsize:35 This text is big"
#+end_src

**** dismissnotify
Dismisses all or up to AMOUNT notifications.

#+begin_src sh
hyprctl dismissnotify # dismiss all notifications
hyprctl dismissnotify 2 # dismiss the oldest 2 notifications
hyprctl dismissnotify -1 # dismiss all notifications (same as no arguments)
#+end_src
*** info
for var to use see:[[https://wiki.hyprland.org/Configuring/Variables/]]
#+begin_src
version - prints the Hyprland version along with flags, commit and branch of build.
monitors - lists active outputs with their properties, 'monitors all' lists active and inactive outputs
workspaces - lists all workspaces with their properties
activeworkspace - gets the active workspace and its properties
workspacerules - gets the list of defined workspace rules
clients - lists all windows with their properties
devices - lists all connected keyboards and mice
decorations [window] - lists all decorations and their info
binds - lists all registered binds
activewindow - gets the active window name and its properties
layers - lists all the layers
splash - prints the current random splash
getoption [option] - gets the config option status (values)
cursorpos - gets the current cursor position in global layout coordinates
animations - gets the currently configured info about animations and beziers
instances - lists all running instances of Hyprland with their info
layouts - lists all layouts available (including from plugins)
configerrors - lists all current config parsing errors
rollinglog - prints tail of the log. Also supports -f/--follow option
locked - prints whether the current session is locked.
descriptions - returns a JSON with all config options, their descriptions and types.
submap - prints the current submap the keybinds are in
#+end_src

**** getoption
For the getoption command, the option name should be written as section:option, e.g.:
#+begin_src sh
hyprctl getoption general:border_size

# For nested sections:
hyprctl getoption input:touchpad:disable_while_typing
#+end_src
*** batch
You can also use --batch to specify a batch of commands to execute.
#+begin_src sh
hyprctl --batch "keyword general:border_size 2 ; keyword general:gaps_out 20"
#+end_src
; separates the commands

*** flags
You can specify flags for the request like this:

#+begin_src sh
hyprctl -j monitors
#+end_src

#+begin_src sh
j -> output in JSON
i -> select instance (id or index in hyprctl instances)
#+end_src
