#+title: mpv configuration

* video output drivers

#+begin_src nix

#

* video sync
audio:	Time video frames to audio. This is the most robust mode, because the player doesn't have to assume anything about how the display behaves. The disadvantage is that it can lead to occasional frame drops or repeats. If audio is disabled, this uses the system clock. This is the default mode.
display-resample:
 	Resample audio to match the video. This mode will also try to adjust audio speed to compensate for other drift. (This means it will play the audio at a different speed every once in a while to reduce the A/V difference.)
display-resample-vdrop:
 	Resample audio to match the video. Drop video frames to compensate for drift.
display-resample-desync:
 	Like the previous mode, but no A/V compensation.
display-tempo:	Same as display-resample, but apply audio speed changes to audio filters instead of resampling to avoid the change in pitch. Beware that some audio filters don't do well with a speed close to 1. It is recommend to use a conditional profile to automatically switch to display-resample when speed gets too close to 1 for your filter setup. Use (speed * video_speed_correction) to get the actual playback speed in the condition. See Conditional auto profiles for details.
display-vdrop:	Drop or repeat video frames to compensate desyncing video. (Although it should have the same effects as audio, the implementation is very different.)
display-adrop:	Drop or repeat audio data to compensate desyncing video. This mode will cause severe audio artifacts if the real monitor refresh rate is too different from the reported or forced rate. Since mpv 0.33.0, this acts on entire audio frames, instead of single samples.
display-desync:	Sync video to display, and let audio play on its own.
desync:	Sync video according to system clock, and let audio play on its own.+end_src
