#+title: mpv configuration
#+startup: content indent
#+auto_tangle: t

* important key binds

|-----+------------------------|
| key | does                   |
|-----+------------------------|
| ?   | pull up mpv cheatsheet |
|-----+------------------------|
** TODO use all scripts

* main config
** into - let
let used to simplify calling my scripts
#+begin_src nix :tangle default.nix
{ pkgs, osConfig, ... }:
let
#+end_src

*** mpvScripts
see if quality-menu is needed with modernX uosc
#+begin_src nix :tangle default.nix
mpvScripts = with pkgs.mpvScripts; [
  mpris
  # mpv-discord #TODO too much work lol
  # sponsorblock # TODO not need?
  quality-menu # allows you to change the streamed video and audio quality (ytdl-format) on the fly.
  youtube-upnext # C-u (configurablea) , space to append
  mpv-cheatsheet # use ?
  mpv-playlistmanager # S-Enter to add to playlist
  # uosc
  modernx-zydezu
  thumbfast # thumbnails
];
#+end_src

*** how some of it looks
*** mpv playlistManager
○ default file
▷ playing file
● hovered file(for removing, playing and moving)
▶ playing and hovered file
➔ selected file(file is being moved)
➤ playing and selected file
** start mpv
#+begin_src nix :tangle default.nix
in
{
  programs.mpv = {
    enable = true;
#+end_src

** scripts, scriptOpts
see:
*** start
#+begin_src nix :tangle default.nix
scripts = mpvScripts;
scriptOpts = {
#+end_src

**** discord rich presence
#+begin_src nix :tangle no
mpv_discordRPC = {
  rpc_wrapper = "lua-discordRPC";
  periodic_timer = 1;
  cover_art = true;
  active = true;
  key_toggle = "D";
};
#+end_src

*** uosc
#+begin_src nix :tangle no
uosc = import ./scripts/uosc.nix;
#+end_src
*** modernX-zydezu
#+begin_src nix :tangle default.nix
modernx-zydezu = import ./scriptOpts/modernx-zydezu.nix;
#+end_src
*** playlistmanager
#+begin_src nix :tangle default.nix
playlistmanager = import ./scriptOpts/playlistManager.nix;
#+end_src
*** end
#+begin_src nix :tangle default.nix
};
#+end_src
** key binds
[[file:keybindings.nix][./keybindings.nix]] written to mpv/input.conf

#+begin_src nix :tangle default.nix
bindings = import ./keybindings.nix // {
  Y = "script-binding quality_menu/video_formats_toggle";
  # Alt+f script-binding quality_menu/audio_formats_toggle
};
#+end_src

*** extra input
appended to mpv/input.conf
#+begin_src nix :tangle default.nix
extraInput = ''
 b  quit #! Quit
'';
#+end_src

** profiles
#+begin_src nix :tangle default.nix
profiles = {
  # mpv/mpv.conf
  fast = {
    vo =
      if osConfig.networking.hostName == "carthage" then
        "vaapi"
      else if osConfig.networking.hostName == "tangier" then
        # "vdpau"
        "nvdec"
      else
        "";
  }; # video output backend to use
};
#+end_src

** configuration
written to: .config/mpv/mpv.conf
*** config start
#+begin_src nix :tangle default.nix
config = {
#+end_src

*** osd
#+begin_src nix :tangle default.nix
osd-on-seek = false;
osd-font = "VictorMono Nerd Font";
osd-font-size = 38; # 55::
osd-bar = false; # nice with uosc
osc = false; # for modernx
#+end_src

*** audio device
#+begin_src nix :tangle default.nix
audio-device =
  if osConfig.networking.hostName == "carthage" then
    "pipewire/alsa_output.pci-0000_09_00.3.analog-stereo"
  else if osConfig.networking.hostName == "tangier" then
    "pipewire/alsa_output.pci-0000_00_1b.0.analog-stereo"
  else
    "pipewire"; # FIXME no default option test further
# --audio-device=help
#audio-pitch-correction=no # Do not filter audio to keep pitch when changing playback speed.
#+end_src

*** full screen
#+begin_src nix :tangle default.nix
fs = false; # fullscreen
# fs-screen = # all, current, 0-32
# keep-open = true; # after playback ends - TODO make script for youtube. close otherwise
# livemarkers = #FIXME test if failed
#   if osConfig.networking.hostName == "carthage" then
#     true
#   else if osConfig.networking.hostName == "tangier" then
#     false
#   else
#     false;
# force-window = false; # FIXME not working for audio # immediate, true, | Do not wait with showing the video window until it has loaded. (This will resize the window once video is loaded. Also always shows a window with audio.)
# sub-bold = true;
#+end_src

*** profile
#+begin_src nix :tangle default.nix
profile =
  if osConfig.networking.hostName == "carthage" then
    "high-quality"
  else if osConfig.networking.hostName == "tangier" then
    "fast"
  else
    "";
gpu-context = "wayland";
#+end_src

*** video sync
#+begin_src nix :tangle default.nix
video-sync =
  if osConfig.networking.hostName == "carthage" then
    "display-resample"
  else if osConfig.networking.hostName == "tangier" then
    "audio"
  else
    "audio";
#+end_src

*** video output drivers + hardware decoding

#+begin_src nix :tangle default.nix
hwdec = "auto"; # hardware decoding, auto,auto-safe, vaapi (unsafe), set vaapi only if necessary
vo =
  # video output drivers experimental (gpu-next ) should be better, gpu,NOTE vaapi lowquality, vdpau -x11
  if osConfig.networking.hostName == "carthage" then
    "gpu-next"
  else if osConfig.networking.hostName == "tangier" then
    "gpu"
  else
    "gpu";
#+end_src

**** notes
***** hwdec
hardware decoding api
 - whether decoding is done is based on the video codec, if not possible fallback to software
 - disabled by default

no:  always use software decoding (default)
auto:  enable any whitelisted hw decoder (see below)
auto-unsafe:  forcibly enable any hw decoder found (see below)
yes:  exactly the same as auto
auto-safe:  exactly the same as auto

***** video output drivers
vo - video output backend to use. [[https://mpv.io/manual/stable/#video-output-drivers]]
+ gpu
  * General purpose, customizable, GPU-accelerated video output driver. It supports extended scaling methods, dithering, color management, custom shaders, HDR, and more.
  * provides predefined profils (fast + high-quality) select with --profile=<name>
+ gpu-next
  + experimental video renderer based on libplacebo
  + supports almost the same set of features as --vo=gpu
  + generally be faster/higher quality but experimental still

*** ytdl, quality of the video
#+begin_src nix :tangle default.nix
# ytdl-format = "bestvideo+bestaudio"; # ytdl,"best"  worst, mp4, webm (Default: bestvideo+bestaudio/best)
ytdl-format = "bv*[height<=1080]+ba/b[height<=1080]"; # ytdl,"best"  worst, mp4, webm (Default: bestvideo+bestaudio/best)
#+end_src

*** cache  + demux
#+begin_src nix :tangle default.nix
cache = true; # yes, no , auto
cache-pause = true; # buffering insteaad of stutter :)
cache-pause-initial = true;
demuxer-max-bytes = "512MiB";
demuxer-max-back-bytes = "100M";
demuxer-readahead-secs = 20;
# Store cache payload on the hard disk instead of in RAM. (This may negatively
# impact performance unless used for slow input such as network.)
#cache-dir=~/.cache/
#cache-on-disk=yes
# cache-default = 4000000; # not found?
#+end_src

*** languages, sub languages, audio languages, video languages + subtitles
#+begin_src nix :tangle default.nix
slang = "en"; # Display English subtitles if available.
alang = [
  "jpn"
  "en"
];
vlang = [ "jpn" "en" ];
# sub-auto = "fuzzy";
sub-font = "VictorMono Nerd Font";
sub-font-size = 40; # 55::The unit is the size in scaled pixels at a window height of 720. The actual pixel size is scaled with the window height: if the window height is larger or smaller than 720, the actual size of the text increases or decreases as well.
# sub-bold = true;
sub-pos = 100; # 0-150. 100 original - % vertical. >100 sub down
subs-match-os-language = true; #TODO test this further
subs-fallback = true; # if noo match select a full track
#+end_src

**** notes
+ vlang - Equivalent to --alang and --slang, for video tracks.
+ slang - Equivalent to --alang, for subtitle tracks.
*** subtitles
#+begin_src nix :tangle default.nix
#+end_src

*** watch later , resume playback
#+begin_src nix :tangle default.nix
save-position-on-quit = true;
watch-later-dir = "~/Videos/mpv-watch-later";
resume-playback = true; # resume-playback-check-mtime - use incase of similar name to match mtime with statefile
# thumbnails = "best"; # all, best , none:: #FIXME failed
#+end_src

*** volume
#+begin_src nix :tangle default.nix
volume = 70; # startup volume
volume-max = 100;
gapless-audio = true; # no, yes, weak:: #Try to play consecutive audio files with no silence or disruption at the point of file change
#+end_src

*** misc
#+begin_src nix :tangle default.nix
border = false; # for mordernx etc
embeddedfonts = true;
screenshot-format = "png"; # jpeg, png, webp, avif, jxl
# dither = true; #   Can help reduce banding artifacts, especially in 8-bit content.
#+end_src

*** end of config
#+begin_src nix :tangle default.nix
}; # end of config
 # extraInput = #sub config append to mpv/input.conf
 # ''
 # '';
#+end_src

** end of mpv
#+begin_src nix :tangle default.nix
}; # end of mpv
} # EOF
#+end_src

* plugin-opts
** uosc
*** config
#+begin_src nix :tangle scriptOpts/uosc.nix
{
  # Display style of current position. available: line, bar
  timeline_style = "line";
  # Line display style config
  timeline_line_width = 2;
  # Render cache indicators for streaming content
  timeline_cache = true;
  controls = "menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality, gap, space, space, shuffle, loop-playlist, loop-file, gap, prev, items, next, gap, fullscreen";
  # Where to display volume controls: none, left, right
  volume = "none";
  volume_size = 20;
  volume_border = 1;
  volume_step = 1;
  #volume_persistency=
  ## Playback speed widget: mouse drag or wheel to change, click to reset
  speed_step = 0.4;
  speed_step_is_factor = false;
  # speed_persistency=

  # If there's no playlist and file ends, load next file in directory
  # Uses `load_types` config below to determine what type of file to load next.
  # When enabled, usoc will set mpv config `keep-open` to `yes`, and `keep-open-pause` to `no`.
  autoload = true;
  # Enable uosc's playlist/directory shuffle mode
  # This simply makes the next selected playlist or directory item be random, just
  # like any other player in the world. It also has an easily togglable control button.
  shuffle = true;

  # Move files to trash (recycle bin) when deleting files. Dependencies:
  # - Linux: `sudo apt install trash-cli`
  # - MacOS: `brew install trash`
  use_trash = true;
  default_directory = "~/";
  #
  # Localization language priority from highest to lowest.
  # Also controls what languages are fetched by `download-subtitles` menu.
  # Built in languages can be found in `uosc/intl`.
  # `slang` is a keyword to inherit values from `--slang` mpv config.
  # Supports paths to custom json files: `languages=~~/custom.json,slang,en`
  languages = [
    "slang"
    "en"
  ];
  # By default, subtitles are downloaded into the directory of currently opened file.
  # If the file is being played from a URL, we use this directory instead (expands to `{mpv_config_dir}/subtitles`)
  # Prefix the path with `!` to force all subtitles to be saved there. Example: `!~~/subtitles`
  subtitles_directory = "~~/subtitles";

  # Use only bold font weight throughout the whole UI
  font_bold = false;
  # One of `total`, `playtime-remaining` (scaled by the current speed), `time-remaining` (remaining length of file)
  destination_time = "playtime-remaining";
  # Display sub second fraction in timestamps up to this precision
  time_precision = 0;
  # Display stream's buffered time in timeline if it's lower than this amount of seconds, 0 to disable
  buffered_time_threshold = 60;
  # Hide UI when mpv autohides the cursor. Timing is controlled by `cursor-autohide` in `mpv.conf` (in milliseconds).
  autohide = true;
  # Can be: flash, static, manual (controlled by flash-pause-indicator and decide-pause-indicator commands)
  pause_indicator = "static";
  # Sizes to list in stream quality menu
  # stream_quality_options = "4320,2160,1440,1080,720,480,360,240,144";
  stream_quality_options = "1080,720";
  # Types to identify media files
  video_types = "3g2,3gp,asf,avi,f4v,flv,h264,h265,m2ts,m4v,mkv,mov,mp4,mp4v,mpeg,mpg,ogm,ogv,rm,rmvb,ts,vob,webm,wmv,y4m";
  audio_types = "aac,ac3,aiff,ape,au,cue,dsf,dts,flac,m4a,mid,midi,mka,mp3,mp4a,oga,ogg,opus,spx,tak,tta,wav,weba,wma,wv";
  image_types = "apng,avif,bmp,gif,j2k,jp2,jfif,jpeg,jpg,jxl,mj2,png,svg,tga,tif,tiff,webp";
  subtitle_types = "aqt,ass,gsub,idx,jss,lrc,mks,pgs,pjs,psb,rt,sbv,slt,smi,sub,sup,srt,ssa,ssf,ttxt,txt,usf,vt,vtt";
  playlist_types = "m3u,m3u8,pls,url,cue";
  # Type pools used by file navigation and `autoload` to determine what type of file to load next
  # Available: video,audio,image,playlist,same. `same` means the same type pool (not just extension) as currently open file.
  load_types = [
    "video"
    "audio"
    # "image"
  ];

  # A comma separated list of element IDs to disable. Available IDs:
  #   window_border, top_bar, timeline, controls, volume,
  #   idle_indicator, audio_indicator, buffering_indicator, pause_indicator
  # disable_elements=
  #
  ## List of mpv.conf properties respected by uosc:
  # osd-font, osd-playlist-entry, slang

  controls_size = 32;
  controls_margin = 8;
  controls_spacing = 2;
  # controls_persistency=
}
#+end_src
*** default shortcuts uosc
not part of the setup

#+begin_src conf
menu        script-binding uosc/menu
mbtn_right  script-binding uosc/menu
s           script-binding uosc/subtitles          #! Subtitles
a           script-binding uosc/audio              #! Audio tracks
q           script-binding uosc/stream-quality     #! Stream quality
p           script-binding uosc/items              #! Playlist
c           script-binding uosc/chapters           #! Chapters
>           script-binding uosc/next               #! Navigation > Next
<           script-binding uosc/prev               #! Navigation > Prev
alt+>       script-binding uosc/delete-file-next   #! Navigation > Delete file & Next
alt+<       script-binding uosc/delete-file-prev   #! Navigation > Delete file & Prev
alt+esc     script-binding uosc/delete-file-quit   #! Navigation > Delete file & Quit
o           script-binding uosc/open-file          #! Navigation > Open file
#           set video-aspect-override "-1"         #! Utils > Aspect ratio > Default
#           set video-aspect-override "16:9"       #! Utils > Aspect ratio > 16:9
#           set video-aspect-override "4:3"        #! Utils > Aspect ratio > 4:3
#           set video-aspect-override "2.35:1"     #! Utils > Aspect ratio > 2.35:1
#           script-binding uosc/audio-device       #! Utils > Audio devices
#           script-binding uosc/editions           #! Utils > Editions
ctrl+s      async screenshot                       #! Utils > Screenshot
alt+i       script-binding uosc/keybinds           #! Utils > Key bindings
O           script-binding uosc/show-in-directory  #! Utils > Show in directory
#           script-binding uosc/open-config-directory #! Utils > Open config directory
#           script-binding uosc/update             #! Utils > Update uosc
esc         quit #! Quit
# Alt+f script-binding quality_menu/audio_formats_toggle
#+end_src

*** source
#see: https://github.com/tomasklaen/uosc/blob/HEAD/src/uosc.conf

** modernx
** modernx-zydezu
*** misc
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
{
  compact_mode = true;
  info_button = false;
  title_font_size = 15;
  seekbar_handle_size = 0;
  jump_buttons = false;                    # show the jump backward and forward buttons
  window_top_bar = false;                # show OSC window top bar: "auto", "yes", or "no" (borderless/fullscreen)
  ontop_button = false;                    # show window on top button
  screenshot_button = false;
  loop_in_pause = false; # dontt think i need
  playpause_size = 30;                    # icon size for the play/pause button
  midbuttons_size = 24;                   # icon size for the middle buttons
  sidebuttons_size = 24;                  # icon size for the side buttons
#+end_src

*** persistent progress
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
persistent_progress = true;            # always show a small progress line at the bottom of the screen
persistent_progressheight = 37;         # the height of the persistent_progress bar
persistent_buffer = true;              # on web videos, show the buffer on the persistent progress line
persistent_progresstoggle = true;       # enable toggling the persistent_progress bar
#+end_src

*** downloads
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
download_button = true;                 # show download button on web videos (requires yt-dlp and ffmpeg)
# download_path = "~~desktop/mpv/downloads"; # default download directory for videos (https://mpv.io/manual/master/#paths)
download_path = "~/Videos/mpvDownloads"; # default download directory for videos (https://mpv.io/manual/master/#paths)
}
#+end_src
** playlistmanager
#+begin_src nix :tangle scriptOpts/playlistManager.nix
# KEY show-text "Shuffled playlist" ; script-message playlistmanager shuffle
{
  p = "show-text 'Shuffled playlist'; script-message playlistmanager shuffle";
  l = "loadfiles";
}
#+end_src
* video sync
- audio: Time video frames to audio. This is the most robust mode, because the player doesn't have to assume anything about how the display behaves. The disadvantage is that it can lead to occasional frame drops or repeats. If audio is disabled, this uses the system clock. This is the default mode.
- display-resample:
   Resample audio to match the video. This mode will also try to adjust audio speed to compensate for other drift. (This means it will play the audio at a different speed every once in a while to reduce the A/V difference.)
- display-resample-vdrop:
   Resample audio to match the video. Drop video frames to compensate for drift.
- display-resample-desync:
   Like the previous mode, but no A/V compensation.
- display-tempo:  Same as display-resample, but apply audio speed changes to audio filters instead of resampling to avoid the change in pitch. Beware that some audio filters don't do well with a speed close to 1. It is recommend to use a conditional profile to automatically switch to display-resample when speed gets too close to 1 for your filter setup. Use (speed * video_speed_correction) to get the actual playback speed in the condition. See Conditional auto profiles for details.
- display-vdrop:  Drop or repeat video frames to compensate desyncing video. (Although it should have the same effects as audio, the implementation is very different.)
- display-adrop:  Drop or repeat audio data to compensate desyncing video. This mode will cause severe audio artifacts if the real monitor refresh rate is too different from the reported or forced rate. Since mpv 0.33.0, this acts on entire audio frames, instead of single samples.
- display-desync:  Sync video to display, and let audio play on its own.
- desync:  Sync video according to system clock, and let audio play on its own.+end_src

* extra notes
** play playlists
- use =#playlist=<filename>= - supports common formats
- use =#playlist-start=<auto|index>= to set file to play in internal playlist
  - *index* is an int
  - 0 - first file
  - behavior undefined and may change if:
    - index does not exist
    - if playlist has further playlists
*** text file requirements
- files delimited by new line

** interesting flags
+ =#list-options=
+ =#list--properties=
+ =#no-config=
+ =#idle= - Makes mpv wait idly instead of quitting when there is no file to play. Mostly useful in input mode, where mpv can be controlled through input commands

** see also:
  - [[https://mpv.io/manual/stable/#synopsis][mpv official docs#synopsis]]
  - [[https://mpv.io/manual/stable/#lua-scripting][lua scripting | mpv manual]]
