#+title: mpv configuration
#+startup: content indent
#+auto_tangle: t

* important key binds

|-----+------------------------|
| key | does                   |
|-----+------------------------|
| ?   | pull up mpv cheatsheet |
|-----+------------------------|
** TODO use all scripts

* main config
** into - let
let used to simplify calling my scripts
#+begin_src nix :tangle default.nix
{ pkgs, osConfig, ... }:
let
#+end_src

*** mpvScripts
see if quality-menu is needed with modernX uosc
#+begin_src nix :tangle default.nix
mpvScripts = with pkgs.mpvScripts; [
  mpris
  # mpv-discord #TODO too much work lol
  # sponsorblock # TODO not need?
  quality-menu # allows you to change the streamed video and audio quality (ytdl-format) on the fly.
  youtube-upnext # C-u (configurablea) , space to append
  mpv-cheatsheet # use ?
  mpv-playlistmanager # S-Enter to add to playlist
  # uosc
  modernx-zydezu
  thumbfast # thumbnails
];
#+end_src

*** how some of it looks
*** mpv playlistManager
○ default file
▷ playing file
● hovered file(for removing, playing and moving)
▶ playing and hovered file
➔ selected file(file is being moved)
➤ playing and selected file
** start mpv
#+begin_src nix :tangle default.nix
in
{
  programs.mpv = {
    enable = true;
#+end_src

** scripts, scriptOpts
see:
*** start
#+begin_src nix :tangle default.nix
scripts = mpvScripts;
scriptOpts = {
#+end_src

**** discord rich presence
#+begin_src nix :tangle no
mpv_discordRPC = {
  rpc_wrapper = "lua-discordRPC";
  periodic_timer = 1;
  cover_art = true;
  active = true;
  key_toggle = "D";
};
#+end_src

*** uosc
#+begin_src nix :tangle no
uosc = import ./scripts/uosc.nix;
#+end_src
*** modernX-zydezu
#+begin_src nix :tangle default.nix
modernx-zydezu = import ./scriptOpts/modernx-zydezu.nix;
#+end_src
*** playlistmanager
#+begin_src nix :tangle default.nix
playlistmanager = import ./scriptOpts/playlistManager.nix;
#+end_src
*** end
#+begin_src nix :tangle default.nix
};
#+end_src
** key binds
written to mpv/input.conf
*** starter
#+begin_src nix :tangle default.nix
bindings = {
#+end_src

*** misc
#+begin_src nix :tangle default.nix
Y = "script-binding quality_menu/video_formats_toggle";
# Alt+f script-binding quality_menu/audio_formats_toggle
# "ctrl+a" = "script-message osc-visibility cycle";
# "ctrl+f" = "script-binding subtitle_lines/list_subtitles";
# "tab" = "script-binding uosc/toggle-ui";
# "menu" = "script-binding uosc/menu";
# "mbtn_right" = "script-binding uosc/menu";
# "mbtn_left" = "space cycle pause; show-text \"\${filename}\n\${time-pos} / \${duration} (\${percent-pos}%)\"; osd-bar show-progress";
"mbtn_left" = "cycle pause; show-progress";
"ctrl+s" = "async screenshot"; # ! Utils > Screenshot
"esc" = "quit"; # ! Quit
#+end_src

*** uosc bindings
#+begin_src nix :tangle no
# "s" = "script-binding uosc/subtitles"; # ! Subtitles
# "a" = "script-binding uosc/audio"; # ! Audio tracks
# "q" = "script-binding uosc/stream-quality"; # ! Stream quality
# "p" = "script-binding uosc/items"; # ! Playlist
# "c" = "script-binding uosc/chapters"; # ! Chapters
# "alt+>" = "script-binding uosc/delete-file-next"; # ! Navigation > Delete file & Next
# "alt+<" = "script-binding uosc/delete-file-prev"; # ! Navigation > Delete file & Prev
# "alt+esc" = "script-binding uosc/delete-file-quit"; # ! Navigation > Delete file & Quit
# "o" = "script-binding uosc/open-file"; # ! Navigation > Open file
#           set video-aspect-override "-1"         #! Utils > Aspect ratio > Default
#           set video-aspect-override "16:9"       #! Utils > Aspect ratio > 16:9
#           set video-aspect-override "4:3"        #! Utils > Aspect ratio > 4:3
#           set video-aspect-override "2.35:1"     #! Utils > Aspect ratio > 2.35:1
#           script-binding uosc/audio-device       #! Utils > Audio devices
#           script-binding uosc/editions           #! Utils > Editions
# "alt+i" = "script-binding uosc/keybinds"; # ! Utils > Key bindings
# "O" = "script-binding uosc/show-in-directory"; # ! Utils > Show in directory
#           script-binding uosc/open-config-directory #! Utils > Open config directory
#           script-binding uosc/update             #! Utils > Update uosc
#+end_src

*** ender
#+begin_src nix :tangle default.nix
};
#+end_src

*** extra input
appended to mpv/input.conf
#+begin_src nix :tangle default.nix
extraInput = ''
 b  quit #! Quit
'';
#+end_src

** profiles
#+begin_src nix :tangle default.nix
profiles = {
  # mpv/mpv.conf
  fast = {
    vo =
      if osConfig.networking.hostName == "carthage" then
        "vaapi"
      else if osConfig.networking.hostName == "tangier" then
        # "vdpau"
        "nvdec"
      else
        "";
  }; # video output backend to use
};
#+end_src

** configuration
written to: .config/mpv/mpv.conf
*** config start
#+begin_src nix :tangle default.nix
config = {
#+end_src

*** osd
#+begin_src nix :tangle default.nix
osd-on-seek = false;
osd-font = "VictorMono Nerd Font";
osd-font-size = 38; # 55::
osd-bar = false; # nice with uosc
osc = false; # for modernx
#+end_src

*** audio device
#+begin_src nix :tangle default.nix
audio-device =
  if osConfig.networking.hostName == "carthage" then
    "pipewire/alsa_output.pci-0000_09_00.3.analog-stereo"
  else if osConfig.networking.hostName == "tangier" then
    "pipewire/alsa_output.pci-0000_00_1b.0.analog-stereo"
  else
    "pipewire"; # FIXME no default option test further
# --audio-device=help
#audio-pitch-correction=no # Do not filter audio to keep pitch when changing playback speed.
#+end_src

*** full screen
#+begin_src nix :tangle default.nix
fs = false; # fullscreen
# fs-screen = # all, current, 0-32
# keep-open = true; # after playback ends - TODO make script for youtube. close otherwise
# livemarkers = #FIXME test if failed
#   if osConfig.networking.hostName == "carthage" then
#     true
#   else if osConfig.networking.hostName == "tangier" then
#     false
#   else
#     false;
# force-window = false; # FIXME not working for audio # immediate, true, | Do not wait with showing the video window until it has loaded. (This will resize the window once video is loaded. Also always shows a window with audio.)
# sub-bold = true;
#+end_src

*** profile
#+begin_src nix :tangle default.nix
profile =
  if osConfig.networking.hostName == "carthage" then
    "high-quality"
  else if osConfig.networking.hostName == "tangier" then
    "fast"
  else
    "";
gpu-context = "wayland";
#+end_src

*** video sync
#+begin_src nix :tangle default.nix
video-sync =
  if osConfig.networking.hostName == "carthage" then
    "display-resample"
  else if osConfig.networking.hostName == "tangier" then
    "audio"
  else
    "audio";
#+end_src

*** video output drivers + hardware decoding

#+begin_src nix :tangle default.nix
hwdec = "auto"; # hardware decoding, auto,auto-safe, vaapi (unsafe), set vaapi only if necessary
vo =
  # video output drivers experimental (gpu-next ) should be better, gpu,NOTE vaapi lowquality, vdpau -x11
  if osConfig.networking.hostName == "carthage" then
    "gpu-next"
  else if osConfig.networking.hostName == "tangier" then
    "gpu"
  else
    "gpu";
#+end_src

**** notes
***** hwdec
hardware decoding api
 - whether decoding is done is based on the video codec, if not possible fallback to software
 - disabled by default

no:  always use software decoding (default)
auto:  enable any whitelisted hw decoder (see below)
auto-unsafe:  forcibly enable any hw decoder found (see below)
yes:  exactly the same as auto
auto-safe:  exactly the same as auto

***** video output drivers
vo - video output backend to use. [[https://mpv.io/manual/stable/#video-output-drivers]]
+ gpu
  * General purpose, customizable, GPU-accelerated video output driver. It supports extended scaling methods, dithering, color management, custom shaders, HDR, and more.
  * provides predefined profils (fast + high-quality) select with --profile=<name>
+ gpu-next
  + experimental video renderer based on libplacebo
  + supports almost the same set of features as --vo=gpu
  + generally be faster/higher quality but experimental still

*** ytdl, quality of the video
#+begin_src nix :tangle default.nix
# ytdl-format = "bestvideo+bestaudio"; # ytdl,"best"  worst, mp4, webm (Default: bestvideo+bestaudio/best)
ytdl-format = "bv*[height<=1080]+ba/b[height<=1080]"; # ytdl,"best"  worst, mp4, webm (Default: bestvideo+bestaudio/best)
#+end_src

*** cache  + demux
#+begin_src nix :tangle default.nix
cache = true; # yes, no , auto
cache-pause = true; # buffering insteaad of stutter :)
cache-pause-initial = true;
demuxer-max-bytes = "512MiB";
demuxer-max-back-bytes = "100M";
demuxer-readahead-secs = 20;
# Store cache payload on the hard disk instead of in RAM. (This may negatively
# impact performance unless used for slow input such as network.)
#cache-dir=~/.cache/
#cache-on-disk=yes
# cache-default = 4000000; # not found?
#+end_src

*** languages, sub languages, audio languages, video languages + subtitles
#+begin_src nix :tangle default.nix
slang = "en"; # Display English subtitles if available.
alang = [
  "jpn"
  "en"
];
vlang = [ "jpn" "en" ];
# sub-auto = "fuzzy";
sub-font = "VictorMono Nerd Font";
sub-font-size = 40; # 55::The unit is the size in scaled pixels at a window height of 720. The actual pixel size is scaled with the window height: if the window height is larger or smaller than 720, the actual size of the text increases or decreases as well.
# sub-bold = true;
sub-pos = 100; # 0-150. 100 original - % vertical. >100 sub down
subs-match-os-language = true; #TODO test this further
subs-fallback = true; # if noo match select a full track
#+end_src

**** notes
+ vlang - Equivalent to --alang and --slang, for video tracks.
+ slang - Equivalent to --alang, for subtitle tracks.
*** subtitles
#+begin_src nix :tangle default.nix
#+end_src

*** watch later , resume playback
#+begin_src nix :tangle default.nix
save-position-on-quit = true;
watch-later-dir = "~/Videos/mpv-watch-later";
resume-playback = true; # resume-playback-check-mtime - use incase of similar name to match mtime with statefile
# thumbnails = "best"; # all, best , none:: #FIXME failed
#+end_src

*** volume
#+begin_src nix :tangle default.nix
volume = 70; # startup volume
volume-max = 100;
gapless-audio = true; # no, yes, weak:: #Try to play consecutive audio files with no silence or disruption at the point of file change
#+end_src

*** misc
#+begin_src nix :tangle default.nix
border = false; # for mordernx etc
embeddedfonts = true;
screenshot-format = "png"; # jpeg, png, webp, avif, jxl
# dither = true; #   Can help reduce banding artifacts, especially in 8-bit content.
#+end_src

*** end of config
#+begin_src nix :tangle default.nix
}; # end of config
 # extraInput = #sub config append to mpv/input.conf
 # ''
 # '';
#+end_src

** end of mpv
#+begin_src nix :tangle default.nix
}; # end of mpv
} # EOF
#+end_src

* plugin-opts
** uosc
*** config
#+begin_src nix :tangle scriptOpts/uosc.nix
{
  # Display style of current position. available: line, bar
  timeline_style = "line";
  # Line display style config
  timeline_line_width = 2;
  # Render cache indicators for streaming content
  timeline_cache = true;
  controls = "menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality, gap, space, space, shuffle, loop-playlist, loop-file, gap, prev, items, next, gap, fullscreen";
  # Where to display volume controls: none, left, right
  volume = "none";
  volume_size = 20;
  volume_border = 1;
  volume_step = 1;
  #volume_persistency=
  ## Playback speed widget: mouse drag or wheel to change, click to reset
  speed_step = 0.4;
  speed_step_is_factor = false;
  # speed_persistency=

  # If there's no playlist and file ends, load next file in directory
  # Uses `load_types` config below to determine what type of file to load next.
  # When enabled, usoc will set mpv config `keep-open` to `yes`, and `keep-open-pause` to `no`.
  autoload = true;
  # Enable uosc's playlist/directory shuffle mode
  # This simply makes the next selected playlist or directory item be random, just
  # like any other player in the world. It also has an easily togglable control button.
  shuffle = true;

  # Move files to trash (recycle bin) when deleting files. Dependencies:
  # - Linux: `sudo apt install trash-cli`
  # - MacOS: `brew install trash`
  use_trash = true;
  default_directory = "~/";
  #
  # Localization language priority from highest to lowest.
  # Also controls what languages are fetched by `download-subtitles` menu.
  # Built in languages can be found in `uosc/intl`.
  # `slang` is a keyword to inherit values from `--slang` mpv config.
  # Supports paths to custom json files: `languages=~~/custom.json,slang,en`
  languages = [
    "slang"
    "en"
  ];
  # By default, subtitles are downloaded into the directory of currently opened file.
  # If the file is being played from a URL, we use this directory instead (expands to `{mpv_config_dir}/subtitles`)
  # Prefix the path with `!` to force all subtitles to be saved there. Example: `!~~/subtitles`
  subtitles_directory = "~~/subtitles";

  # Use only bold font weight throughout the whole UI
  font_bold = false;
  # One of `total`, `playtime-remaining` (scaled by the current speed), `time-remaining` (remaining length of file)
  destination_time = "playtime-remaining";
  # Display sub second fraction in timestamps up to this precision
  time_precision = 0;
  # Display stream's buffered time in timeline if it's lower than this amount of seconds, 0 to disable
  buffered_time_threshold = 60;
  # Hide UI when mpv autohides the cursor. Timing is controlled by `cursor-autohide` in `mpv.conf` (in milliseconds).
  autohide = true;
  # Can be: flash, static, manual (controlled by flash-pause-indicator and decide-pause-indicator commands)
  pause_indicator = "static";
  # Sizes to list in stream quality menu
  # stream_quality_options = "4320,2160,1440,1080,720,480,360,240,144";
  stream_quality_options = "1080,720";
  # Types to identify media files
  video_types = "3g2,3gp,asf,avi,f4v,flv,h264,h265,m2ts,m4v,mkv,mov,mp4,mp4v,mpeg,mpg,ogm,ogv,rm,rmvb,ts,vob,webm,wmv,y4m";
  audio_types = "aac,ac3,aiff,ape,au,cue,dsf,dts,flac,m4a,mid,midi,mka,mp3,mp4a,oga,ogg,opus,spx,tak,tta,wav,weba,wma,wv";
  image_types = "apng,avif,bmp,gif,j2k,jp2,jfif,jpeg,jpg,jxl,mj2,png,svg,tga,tif,tiff,webp";
  subtitle_types = "aqt,ass,gsub,idx,jss,lrc,mks,pgs,pjs,psb,rt,sbv,slt,smi,sub,sup,srt,ssa,ssf,ttxt,txt,usf,vt,vtt";
  playlist_types = "m3u,m3u8,pls,url,cue";
  # Type pools used by file navigation and `autoload` to determine what type of file to load next
  # Available: video,audio,image,playlist,same. `same` means the same type pool (not just extension) as currently open file.
  load_types = [
    "video"
    "audio"
    # "image"
  ];

  # A comma separated list of element IDs to disable. Available IDs:
  #   window_border, top_bar, timeline, controls, volume,
  #   idle_indicator, audio_indicator, buffering_indicator, pause_indicator
  # disable_elements=
  #
  ## List of mpv.conf properties respected by uosc:
  # osd-font, osd-playlist-entry, slang

  controls_size = 32;
  controls_margin = 8;
  controls_spacing = 2;
  # controls_persistency=
}
#+end_src
*** default shortcuts uosc
not part of the setup

#+begin_src conf
menu        script-binding uosc/menu
mbtn_right  script-binding uosc/menu
s           script-binding uosc/subtitles          #! Subtitles
a           script-binding uosc/audio              #! Audio tracks
q           script-binding uosc/stream-quality     #! Stream quality
p           script-binding uosc/items              #! Playlist
c           script-binding uosc/chapters           #! Chapters
>           script-binding uosc/next               #! Navigation > Next
<           script-binding uosc/prev               #! Navigation > Prev
alt+>       script-binding uosc/delete-file-next   #! Navigation > Delete file & Next
alt+<       script-binding uosc/delete-file-prev   #! Navigation > Delete file & Prev
alt+esc     script-binding uosc/delete-file-quit   #! Navigation > Delete file & Quit
o           script-binding uosc/open-file          #! Navigation > Open file
#           set video-aspect-override "-1"         #! Utils > Aspect ratio > Default
#           set video-aspect-override "16:9"       #! Utils > Aspect ratio > 16:9
#           set video-aspect-override "4:3"        #! Utils > Aspect ratio > 4:3
#           set video-aspect-override "2.35:1"     #! Utils > Aspect ratio > 2.35:1
#           script-binding uosc/audio-device       #! Utils > Audio devices
#           script-binding uosc/editions           #! Utils > Editions
ctrl+s      async screenshot                       #! Utils > Screenshot
alt+i       script-binding uosc/keybinds           #! Utils > Key bindings
O           script-binding uosc/show-in-directory  #! Utils > Show in directory
#           script-binding uosc/open-config-directory #! Utils > Open config directory
#           script-binding uosc/update             #! Utils > Update uosc
esc         quit #! Quit
# Alt+f script-binding quality_menu/audio_formats_toggle
#+end_src

*** source
#see: https://github.com/tomasklaen/uosc/blob/HEAD/src/uosc.conf

** modernx
** modernx-zydezu
*** start of modernx-zydezu opts
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
{
#+end_src

*** misc
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
title_font_size = 15;
window_top_bar = false;                # show OSC window top bar: "auto", "yes", or "no" (borderless/fullscreen)
loop_in_pause = false; # dontt think i need
#+end_src

*** compact mode, jump buttons, buttons
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
compact_mode = false; # replace the jump buttons with the seek/chapter buttons
jump_buttons = false;                    # show the jump backward and forward buttons
info_button = false;
ontop_button = false;                    # show window on top button
screenshot_button = false;
playpause_size = 30;                    # icon size for the play/pause button
midbuttons_size = 20;                   # icon size for the middle buttons
sidebuttons_size = 20;                  # icon size for the side buttons
track_nextprev_buttons = true;          # show next/previous playlist track buttons

#+end_src
**** button hover
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
    # Button hover effects
    hover_effect = "size,glow,color";       # active button hover effects: "glow", "size", "color"; can use multiple separated by commas
    hover_button_size = 115;                # relative size of a hovered button if "size" effect is active
    button_glow_amount = 5;                 # glow intensity when "glow" hover effect is active
    hover_effect_for_sliders = false;       # apply hover effects to slider handles
#+end_src nix
*** volume control
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
volume_control = false;                  # show mute button and volume slider
volume_control_type = "logarithmic";         # volume scale type: "linear::" or "logarithmic"
#+end_src
*** persistent progress
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
persistent_progress = true;            # always show a small progress line at the bottom of the screen
persistent_progressheight = 37;         # the height of the persistent_progress bar
persistent_buffer = true;              # on web videos, show the buffer on the persistent progress line
persistent_progresstoggle = false;       # enable toggling the persistent_progress bar
#+end_src
*** scale
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
vid_scale = false;                      # scale osc with the video
scale_windowed = 0.8;                   # osc scale factor when windowed
scale_fullscreen = 1.0;                 # osc scale factor when fullscreen
scale_forced_window = 0.8;              # osc scale factor when forced (no video, like music files)
#+end_src

*** downloads
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
download_button = true;                 # show download button on web videos (requires yt-dlp and ffmpeg)
# download_path = "~~desktop/mpv/downloads"; # default download directory for videos (https://mpv.io/manual/master/#paths)
download_path = "~~desktop/Videos/mpvDownloads"; # default download directory for videos (https://mpv.io/manual/master/#paths)
#+end_src

*** Colors and style
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
    osc_color = "#000000";                  # accent color of the OSC and title bar
    window_title_color = "#FFFFFF";         # color of the title in borderless/fullscreen mode
    window_controls_color = "#FFFFFF";      # color of the window controls (close, minimize, maximize) in borderless/fullscreen mode
    window_controls_close_hover = "#E81123"; # color of close window control on hover
    window_controls_minmax_hover = "#53A4FC";# color of min/max window controls on hover
    title_color = "#FFFFFF";                # color of the title (above seekbar)
    seekbarfg_color = "#1D96F5";            # color of the seekbar progress and handle, in Hex color format
    seekbarbg_color = "#FFFFFF";            # color of the remaining seekbar, in Hex color format
    seekbar_cache_color = "#8a2be2";        # color of the cache ranges on the seekbar
    volumebar_match_seek_color = false;     # match volume bar color with seekbar color (ignores side_buttons_color)
    time_color = "#FFFFFF";                 # color of the timestamps (below seekbar)
    chapter_title_color = "#FFFFFF";        # color of the chapter title next to timestamp (below seekbar)
    side_buttons_color = "#FFFFFF";         # color of the side buttons (audio, subtitles, playlist, etc.)
    middle_buttons_color = "#FFFFFF";       # color of the middle buttons (skip, jump, chapter, etc.)
    playpause_color = "#FFFFFF";            # color of the play/pause button
    held_element_color = "#999999";         # color of the element when held down (pressed)
    hover_effect_color = "#FFFFFF";         # color of a hovered button when hover_effect includes "color"
    thumbnail_border_color = "#FFFFFF";     # color of the border for thumbnails (with thumbfast)

    fade_alpha = 150;                       # alpha of the OSC background box
    fade_blur_strength = 100;               # blur strength for the OSC alpha fade. caution: high values can take a lot of CPU time to render
    window_fade_alpha = 75;                 # alpha of the window title bar
    thumbnail_border = 0;                   # the width of the thumbnail border

    # Button hover effects
    hover_effect = "size,glow,color";       # active button hover effects: "glow", "size", "color"; can use multiple separated by commas
    hover_button_size = 115;                # relative size of a hovered button if "size" effect is active
    button_glow_amount = 5;                 # glow intensity when "glow" hover effect is active
#+end_src
*** progress bar
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
# Progress bar settings
    seekbar_handle_size = 0.8;              # size ratio of the seekbar handle (range: 0 ~ 1)
    seek_range = true;                      # show seek range overlay
    seek_rangealpha = 175;                  # transparency of the seek range
    seekbar_keyframes = true;              # use keyframes when dragging the seekbar

    automatic_keyframe_mode = true;         # automatically set keyframes for the seekbar based on video length
    automatic_keyframe_limit = 600;         # videos longer than this (in seconds) will have keyframes on the seekbar
#+end_src
*** end of modernx-zydezu opts
#+begin_src nix :tangle scriptOpts/modernx-zydezu.nix
}
#+end_src
** playlistmanager
#+begin_src nix :tangle scriptOpts/playlistManager.nix
# KEY show-text "Shuffled playlist" ; script-message playlistmanager shuffle
{
  p = "show-text 'Shuffled playlist'; script-message playlistmanager shuffle";
  l = "loadfiles";
}
#+end_src
* video sync
- audio: Time video frames to audio. This is the most robust mode, because the player doesn't have to assume anything about how the display behaves. The disadvantage is that it can lead to occasional frame drops or repeats. If audio is disabled, this uses the system clock. This is the default mode.
- display-resample:
   Resample audio to match the video. This mode will also try to adjust audio speed to compensate for other drift. (This means it will play the audio at a different speed every once in a while to reduce the A/V difference.)
- display-resample-vdrop:
   Resample audio to match the video. Drop video frames to compensate for drift.
- display-resample-desync:
   Like the previous mode, but no A/V compensation.
- display-tempo:  Same as display-resample, but apply audio speed changes to audio filters instead of resampling to avoid the change in pitch. Beware that some audio filters don't do well with a speed close to 1. It is recommend to use a conditional profile to automatically switch to display-resample when speed gets too close to 1 for your filter setup. Use (speed * video_speed_correction) to get the actual playback speed in the condition. See Conditional auto profiles for details.
- display-vdrop:  Drop or repeat video frames to compensate desyncing video. (Although it should have the same effects as audio, the implementation is very different.)
- display-adrop:  Drop or repeat audio data to compensate desyncing video. This mode will cause severe audio artifacts if the real monitor refresh rate is too different from the reported or forced rate. Since mpv 0.33.0, this acts on entire audio frames, instead of single samples.
- display-desync:  Sync video to display, and let audio play on its own.
- desync:  Sync video according to system clock, and let audio play on its own.+end_src

* extra notes
** play playlists
- use =#playlist=<filename>= - supports common formats
- use =#playlist-start=<auto|index>= to set file to play in internal playlist
  - *index* is an int
  - 0 - first file
  - behavior undefined and may change if:
    - index does not exist
    - if playlist has further playlists
*** text file requirements
- files delimited by new line
** default bindings
#+begin_src conf
Keyboard Control
LEFT and RIGHT
Seek backward/forward 5 seconds. Shift+arrow does a 1 second exact seek (see --hr-seek).
UP and DOWN
Seek forward/backward 1 minute. Shift+arrow does a 5 second exact seek (see  --hr-seek).
Ctrl+LEFT and Ctrl+RIGHT
Seek to the previous/next subtitle. Subject to some restrictions and might not always work; see  sub-seek command.
Ctrl+Shift+Left and Ctrl+Shift+Right
Adjust subtitle delay so that the next or previous subtitle is displayed now. This is especially useful to sync subtitles to audio.
[ and ]
Decrease/increase current playback speed by 10%.
{ and }
Halve/double current playback speed.
BACKSPACE
Reset playback speed to normal.
Shift+BACKSPACE
Undo the last seek. This works only if the playlist entry was not changed. Hitting it a second time will go back to the original position. See revert-seek command for details.
Shift+Ctrl+BACKSPACE
Mark the current position. This will then be used by Shift+BACKSPACE as revert position (once you seek back, the marker will be reset). You can use this to seek around in the file and then return to the exact position where you left off.
< and >
Go backward/forward in the playlist.
ENTER
Go forward in the playlist.
p / SPACE
Pause (pressing again unpauses).
.
Step forward. Pressing once will pause, every consecutive press will play one frame and then go into pause mode again.
,
Step backward. Pressing once will pause, every consecutive press will play one frame in reverse and then go into pause mode again.
q
Stop playing and quit.
Q
Like q, but store the current playback position. Playing the same file later will resume at the old playback position if possible.
/ and *
Decrease/increase volume.
9 and 0
Decrease/increase volume.
m
Mute sound.
_
Cycle through the available video tracks.
#
Cycle through the available audio tracks.
f
Toggle fullscreen (see also --fs).
ESC
Exit fullscreen mode.
T
Toggle stay-on-top (see also --ontop).
w and W
Decrease/increase pan-and-scan range. The e key does the same as W currently, but use is discouraged.
o (also P)
Show progression bar, elapsed time and total duration on the OSD.
O
Toggle OSD states between normal and playback time/duration.
v
Toggle subtitle visibility.
j and J
Cycle through the available subtitles.
z and Z
Adjust subtitle delay by +/- 0.1 seconds. The x key does the same as Z currently, but use is discouraged.
l
Set/clear A-B loop points. See ab-loop command for details.
L
Toggle infinite looping.
Ctrl + and Ctrl -
Adjust audio delay (A/V sync) by +/- 0.1 seconds.
u
Switch between applying no style overrides to SSA/ASS subtitles, and overriding them almost completely with the normal subtitle style. See  --sub-ass-override for more info.
V
Toggle subtitle VSFilter aspect compatibility mode. See  --sub-ass-vsfilter-aspect-compat for more info.
r and R
Move subtitles up/down. The t key does the same as R currently, but use is discouraged.
s
Take a screenshot.
S
Take a screenshot, without subtitles. (Whether this works depends on VO driver support.)
Ctrl s
Take a screenshot, as the window shows it (with subtitles, OSD, and scaled video).
PGUP and PGDWN
Seek to the beginning of the previous/next chapter. In most cases, "previous" will actually go to the beginning of the current chapter; see  --chapter-seek-threshold.
Shift+PGUP and Shift+PGDWN
Seek backward or forward by 10 minutes. (This used to be mapped to PGUP/PGDWN without Shift.)
d
Activate/deactivate deinterlacer.
A
Cycle aspect ratio override.
Ctrl h
Toggle hardware video decoding on/off.
Alt+LEFT, Alt+RIGHT, Alt+UP, Alt+DOWN
Move the video rectangle (panning).
Alt + and Alt -
Combining Alt with the + or - keys changes video zoom.
Alt+BACKSPACE
Reset the pan/zoom settings.
F8
Show the playlist and the current position in it (useful only if a UI window is used, broken on the terminal).
F9
Show the list of audio and subtitle streams (useful only if a UI window is used, broken on the terminal).
i and I (and then 0,1,2,3,4 keys to cycle through different stats)
Show/toggle an overlay displaying statistics about the currently playing file such as codec, framerate, number of dropped frames and so on. See STATS for more information.

(The following keys are valid only when using a video output that supports the corresponding adjustment.)
1 and 2
Adjust contrast.
3 and 4
Adjust brightness.
5 and 6
Adjust gamma.
7 and 8
Adjust saturation.
Alt+0 (and command+0 on OSX)
Resize video window to half its original size.
Alt+1 (and command+1 on OSX)
Resize video window to its original size.
Alt+2 (and command+2 on OSX)
Resize video window to double its original size.
command + f (OSX only)
Toggle fullscreen (see also --fs).
(The following keys are valid if you have a keyboard with multimedia keys.)

PAUSE
Pause.
STOP
Stop playing and quit.
PREVIOUS and NEXT
Seek backward/forward 1 minute.
If you miss some older key bindings, look at etc/restore-old-bindings.conf in the mpv git repository.

Mouse Control
button 3 and button 4
Seek backward/forward 1 minute.
button 5 and button 6
Decrease/increase volume.
#+end_src
** interesting flags
+ =#list-options=
+ =#list--properties=
+ =#no-config=
+ =#idle= - Makes mpv wait idly instead of quitting when there is no file to play. Mostly useful in input mode, where mpv can be controlled through input commands

** see also:
  - [[https://mpv.io/manual/stable/#synopsis][mpv official docs#synopsis]]
  - [[https://mpv.io/manual/stable/#lua-scripting][lua scripting | mpv manual]]
