#+title: my ncmpcpp master config
#+auto_tangle: t
#+startup: content indent

* start
#+begin_src nix :tangle default.nix
{pkgs, ...}:
{
  programs.ncmpcpp = {
    enable = true;
    package = pkgs.ncmpcpp.override { visualizerSupport = true; };
#+end_src

* music location
#+begin_src nix :tangle default.nix
    mpdMusicDir = "~/Music";
#+end_src

* bindings
#+begin_src nix :tangle default.nix
  bindings = [
  # scroll
  { key = "j";command = "scroll_down";}
  { key = "k"; command = "scroll_up"; }
  {key = "G"; command = ["move_end"];}
  {key = "K"; command = ["move_home"];}
  {key = "ctrl-g"; command = ["jump_to_browser"];}
  # playlists manipulation
  { key = "J"; command = [ "select_item" "scroll_down" ]; }
  {key = "K"; command = ["select_item" "scroll_up"];}

  {key = "l"; command = "next_column" ;}
  { key = "h"; command = "previous_column"; }

  # { key = "shift-tab"; command = "previous"; }
  # { key = "tab"; command = "next"; }

  ##lyrics
  { key = "'";  command ="show_lyrics" ; } # Had to rebind "l"

  # { key = "^"; command = "toggle_lyrics_fetcher"; }

  # { key = "ctrl-v"; command = "select_range"; }

  # WARN: DANGEROUS
  { key = "d";
    command = [
      "delete_browser_items"
      "delete_playlist_items"
      "delete_stored_playlist"
    ];
  }
  # {key = "0"; command = "run_external_command  \"qs ipc call mpris songArt\"";}
  ];
#+end_src

*** default bindings file
[[file:bindings.org][Ncmpcpp bindings]]
* settings
#+begin_src nix :tangle default.nix
settings = {
#+end_src

** start up
display_screens_numbers_on_start = true; not working

#+begin_src nix :tangle default.nix
startup_screen = "playlist";
user_interface = "classic"; # classic , alternative #TODO: add snippet for nice comments
default_place_to_search_in = "database"; #playlist
#+end_src

** pop up , messages
#+begin_src nix :tangle default.nix
message_delay_time = 2;
connected_message_on_startup = false;
#+end_src

** screen switch
If set to "previous", key_screen_switcher will switch between current and last used screen. If set to "sequence: user_defined_sequence", it will switch between given sequence of screens. Syntax clarification can be found in example config file.

#+begin_src :tangle default.nix
screen_switcher_mode = "previous";
#+end_src

** locked screen part
If enabled, ncmpcpp will ask for % of locked screen's width each time you want to lock a screen. If you disable that, it'll silently attempt to use default value.

#+begin_src nix :tangle default.nix
locked_screen_width_part = "50"; # 20-80::
ask_for_locked_screen_width_part = true; # disable to use default
#+end_src

#+begin_src nix :tangle default.nix
jump_to_now_playing_song_at_start = true;
#now_playing_prefix = " "; # 󱉺  
now_playing_prefix = " ";#TODO:check how to filter out songs from playlist
now_playing_suffix = "  ";
#+end_src

** external editor
#+begin_src nix :tangle default.nix
external_editor = "/home/malu/.nix-profile/bin/emacsclient -nc";
use_console_editor = true;#TODO: what is sit doing?
#+end_src

** cursor position
#+begin_src nix :tangle default.nix
# functionality
centered_cursor = true; #playing focus
autocenter_mode = true; # Centers highlight on current song during switch


#+end_src


+ centered_cursor = yes/no
        If enabled, currently highlighted position in the list will be always centered.

+ autocenter_mode = yes/no
        Default state for autocenter mode at start.
** misc
#+begin_src nix :tangle default.nix
block_search_constraints_change_if_items_found = true; # fields in Search engine above "Reset" will be blocked after successful searching

cyclic_scrolling = true;

display_bitrate = false;

enable_window_title = true;

ignore_diacritics = true; # local language ^ pronounciation marker eg. shadda, umlauts TODO : investigate if this is what is causing issues with -

ignore_leading_the = true;
#+end_src
** tags
#+begin_src nix :tangle default.nix
tag_editor_extended_numeration = true;
empty_tag_marker = "❌";
#empty_tag_color = "";
#+end_src

** media library
media_library_left_column = "a";#a/y/g/c/p - not work
 
#+begin_src nix :tangle default.nix
media_library_primary_tag = "genre"; #album_artist, artist, date, genre, composer, performer
media_library_albums_split_by_date = true;
media_library_hide_album_dates = true;
# media_library_disable_two_column_mode = false; # false::
#+end_src

** find
#+begin_src nix :tangle default.nix
default_find_mode = "wrapped"; #wrapped - go to match as you type, normal <key>w
#+end_src

** lyrics
#+begin_src nix :tangle default.nix
lyrics_directory = "~/Music/ncmpcpp/lyrics";
store_lyrics_in_song_dir = false;
fetch_lyrics_for_current_song_in_background = false;

lyrics_fetchers = "genius , azlyrics";
# lyrics_fetchers = "genius";
follow_now_playing_lyrics = true;
#+end_src

** seeking
#+begin_src nix :tangle default.nix
incremental_seeking = "yes";
seek_time = "1";
#+end_src

** title
If enabled, column titles will be displayed, otherwise hidden.

#+begin_src nix :tangle default.nix
titles_visibility = false;
#+end_src

** header
#+begin_src nix :tangle default.nix
header_text_scrolling = true;
header_visibility = true; # If enabled, header window will be displayed, otherwise hidden.
#+end_src

** colors | list format
*** Non-localized area
**** enable colors
#+begin_src nix :tangle default.nix
colors_enabled = true;
#+end_src

**** color1, color2
color1 -> One of colors used in Song info, Tiny tag editor and Search engine.

#+begin_src nix :tangle default.nix
color1 = 112;                   
color2 = 136;                   # Current Screen , playlist length
#+end_src

**** list/column format
***** column list
NOTE alternatives dont work in column list

#+begin_src nix :tangle default.nix
# song_columns_list_format = "(40)[39]{t} | (30)[39]{a} | (30)[39]{f} (25)[39]{b} (5)[39]{l}"; # clean

song_columns_list_format = "(40)[39]{t} | (30)[39]{a} | (25)[39]{b} (5)[39]{l}"; # clean

# song_columns_list_format = "(40)[7]{t} (30)[7]{a} (25)[7]{b} (5)[7]{l}"; # 39,38

# song_columns_list_format = "(40)[46]{t} (30)[46]{a} (25)[46]{b} (5)[46]{l}"; # 39,38
#+end_src

***** song list
#+begin_src nix :tangle default.nix
song_list_format = "{$5%t} | {$6%f$9} $r %p %b      {$4%a$1$9}$9";
#+end_src

***** current item
#+begin_src nix :tangle default.nix
current_item_prefix = "$(142)$r"; # highlight current
#+end_src

***** current item-inactive
#+begin_src nix :tangle default.nix
current_item_inactive_column_prefix = "$(24)$r"; #nice purp
#+end_src

**** window border color, active window border
#+begin_src nix :tangle default.nix
window_border_color = 212; #pop up windows
active_window_border = 21;
#+end_src

**** main window
Used in playlists/media/add-to-playylist views

#+begin_src nix :tangle default.nix
main_window_color = 69;          # add-menu , 69, 44
#+end_src

**** visualizer
#+begin_src nix :tangle default.nix
visualizer_output_name = "Visualizer feed";
visualizer_type = "wave_filled"; # wave, wave_filled, spectrum, ellipse
visualizer_in_stereo = "yes"; # yes if fifo set to 44100:16:2
visualizer_autoscale = true;
visualizer_spectrum_smooth_look = true;
# visualizer_color = "25, 38, 10";
visualizer_color = "25, 38, 104";
visualizer_look = "+|";
# visualizer_look = "●▮";
#+end_src

+ visualizer_fifo_path = PATH
        Path to mpd fifo output. This is needed to make music visualizer work (note that output sound format of this fifo has to be either 44100:16:1 or 44100:16:2, depending on whether you want mono or stereo visualization)
+ visualizer_in_stereo = yes/no
        Should be set to 'yes', if fifo output's format was set to 44100:16:2.
*** Top Area
**** volume
#+begin_src nix :tangle default.nix
volume_color = 214;             # 124 (green)
display_volume_level = true;
volume_change_step = 2;
#+end_src
**** header
#+begin_src nix :tangle default.nix
header_window_color = 136; # page title #holy purplee
#+end_src

**** alternative header
#+begin_src nix :tangle default.nix
alternative_header_first_line_format = "$0$aqqu$/a$9  {$6%a$9     }{$5%t$9}|{$3%f$9}  $0$atqq$/a$9";
alternative_header_second_line_format = "{{$7%b$9}}|{$4%d$9}";
alternative_ui_separator_color = 1;
#+end_src
**** state line
state flags color mpc status flags eg [rzxu]

#+begin_src nix :tangle default.nix
state_line_color = 1;
state_flags_color = 4; # mpc status flags eg rzxu
#+end_src

*** Bottom Area
**** player state - play/pause
31 - greenish
#+begin_src nix :tangle default.nix
player_state_color = 136; # playing/paused status
#+end_src

**** status bar || curent playing song, time
#+begin_src nix :tangle default.nix
statusbar_time_color = 87;
statusbar_color = 221; # 227 song name on status bar
statusbar_visibility = true;
#+end_src
**** remaining time
#+begin_src nix :tangle default.nix
display_remaining_time = false; #instead of elapsed in status bar
#+end_src
**** progress bar
#+begin_src nix :tangle default.nix
progressbar_color = 24;
# progressbar_look = "─⊙┄";
progressbar_look = "─⊙ ";
#progressbar_look = "─░─";
progressbar_elapsed_color = 74;
#progressbar_elapsed_color = 24; # muted
#+end_src

*** docs
**** song format

#+begin_src
%l - length
%f - filename
%F - full filepath
%D - directory
%a - artist
%A - album artist
%t - title
%b - album
%y - date
%n - track number (01/12 -> 01)
%N - full track info (01/12 -> 01/12)
%g - genre
%c - composer
%p - performer
%d - disc
%C - comment
%P - priority
$R - begin right alignment
#+end_src

You can also put them in ={ }= and then they will be displayed only if all requested values are available and/or define alternate value with ={ }|{ }= e.g.

={%a - %t}|{%f}= will check if artist and title tags are available and if they are, display them. Otherwise it'll display filename.

Note: If you want to set limit on maximal length of a tag, just put the appropriate number between % and character that defines tag type, e.g. to make album take max. 20 terminal cells, use =%20b=.

Note: Format that is similar to "%a - %t" (i.e. without any additional braces) is equal to "{%a - %t}", so if one of the tags is missing, you'll get nothing.

Available values for colors:
- 0 - default window color (discards all other colors)
- 1 - black
- 2 - red
- 3 - green
- 4 - yellow
- 5 - blue
- 6 - magenta
- 7 - cyan
- 8 - white
- 9 - end of current color

Note: colors can be nested, so if you write $2some$5text$9, it'll disable only usage of blue color and make red the current one.

source:[[https://www.mankier.com/1/ncmpcpp#Bindings]]

** playlists
ncmpc_like_songs_adding = true; # If enabled, pressing space on item, which is already in playlist will remove it, otherwise add it again.
#+begin_src nix :tangle default.nix
playlist_disable_highlight_delay = 5; #0 to disable fade
playlist_show_remaining_time = true; #header time remaining
playlist_shorten_total_times = true;
playlist_separate_albums = false; # add separator lines between albums in playlist view
ask_before_clearing_playlists = true;
#+end_src

** display mode , columns
#+begin_src nix :tangle default.nix
search_engine_display_mode = "columns";
browser_display_mode = "columns";
playlist_display_mode = "columns";
playlist_editor_display_mode = "columns";
# browser_playlist_prefix = " - ";
# browser_playlist_prefix = " -> ";
#clock_display_seconds = yes
#+end_src

** mouse
+ mouse_list_scroll_whole_page = yes/no
        If enabled, mouse wheel will scroll the whole page of item list at a time, otherwise the number of lines specified by lines_scrolled variable.

#+begin_src nix :tangle default.nix
lines_scrolled = 8;
mouse_list_scroll_whole_page = true;
mouse_support = true;
#+end_src

** ncmpcpp directory
#+begin_src nix :tangle default.nix
ncmpcpp_directory = "~/.local/share/ncmpcpp";
#+end_src

=ncmpcpp_directory= = PATH
  Directory for storing ncmpcpp related files. Changing it is useful if you want to store everything somewhere else and provide command line setting for alternative location to config file which defines that while launching ncmpcpp.

** mpd settings

+ mpd_communication_mode = MODE

    If set to 'polling', ncmpcpp will constantly poll mpd for its status.

    If set to 'notifications', ncmppcp will make use of 'idle' command and wait for events.

    This is more efficient and responsive, but may cause some trouble with <mpd-0.

    15, so if you run such version and encounter strange bugs (e.g. current track time not being updated), you will either have to use 'polling' or upgrade your mpd.

+ mpd_host = HOST
        Connect to MPD running on specified host/unix socket. When HOST starts with a '/', it is assumed to be a unix socket.

+ mpd_music_dir = PATH
        Search for files in specified directory. This is needed for ~tag editor~ to work.
       
# mpd_communication_mode = "notifications";
not working

#+begin_src nix :tangle default.nix
mpd_crossfade_time = 4;
mpd_connection_timeout = 5;
# mpd_host = "localhost";
mpd_host = "localhost";
mpd_port = 6600;
#+end_src

** on song change
#+begin_src nix :tangle default.nix
execute_on_song_change = "qs ipc call mpris songArt"; # "songart"
#+end_src

** selected prefix tracks
#+begin_src nix :tangle default.nix
selected_item_prefix = "+  ";
discard_colors_if_item_is_selected = true;
#+end_src

** encoding
#+begin_src nix :tangle default.nix
system_encoding = "utf8";
regular_expressions =  "extended"; # none/basic/extended/perl;
generate_win32_compatible_filenames = true; # generated file names eg. with tag editor wont have  \?*:|
#+end_src

** delete files and directories
# allow_physical_directories_deletion = true; not working???

#+begin_src nix :tangle default.nix
allow_for_physical_item_deletion = true;
show_hidden_files_in_local_browser = true;
#+end_src

** Start up screen
#+begin_src nix :tangle default.nix
#startup_slave_screen = "browser";
#+end_src

* end
#+begin_src nix :tangle default.nix
};
 };
  }
#+end_src
