#+auto_tangle: t
#+startup: content indent

* variables
#+begin_src nix :tangle default.nix
{pkgs, osConfig, ...}:
#+end_src

#+begin_src nix :tangle default.nix
{
  wayland.windowManager.hyprland = {
    settings = {
      "$mod" = "SUPER";
      "$formated_rgba" = "$(hyprpicker -f rgb - | sed 's/^/(/; s/$/,1.0)/; y/ /,/' | wl-copy -n)";
      "$cl" = "Control_L";
      "$al" = "Alt_L";
      "$ar" = "Alt_R";
      "$cr" = "Control_R";
      "$sl" = "SHIFT_L";
      "$sr" = "SHIFT_R";
      "$date_short" = "`date +'%I:%M %p'`"; # add -u (utc)
      "$date_long" = "`date +'%a,%d %b%t%I:%M %p'`";
      "$kitty" = "uwsm app -s a -- kitty -1 --instance-group kitty";
      "$yazi_kitty" = "uwsm app -s a -- kitty -1 --instance-group yazi -e yazi";

      "$gaps" = "gaps toggle_gaps_out";
      "$emacs" = "uwsm app -s a -- emacsclient -c";
#+end_src

=rofi=
-sidebar-mode

  #+begin_src nix :tangle default.nix
  "$file_browser_rofi" = "rofi -show filebrowser -filebrowser-command 'xdg-open' -filebrowser-directory '/home/malu' -theme '/home/malu/Shibuya/modules/home/programs/hyprland/keybinds/rofi-themes/fileBrowser.rasi'";
  "$rofi_open_windows" =  "rofi -show window -theme-str 'window {width : 920px;}' -theme-str 'listview {lines:15; dynamic: true;}' -theme-str 'element {background-image: linear-gradient(white/5%, white/10%);border-color: lightblue /15%;}'" ;
  "$menu_rofi" = "rofi -show drun -theme-str 'listview {require-input: true;}'";
  "$emoji_rofi" = "rofi -show emoji";
  "$clip_rofi" = "cliphist list | rofi -dmenu -theme-str 'window {width : 750px;}' -p '' | cliphist decode | wl-copy";
  "$calc_rofi" = "rofi -show calc -p '🪓' -theme-str 'listview {require-input: true;}'";
#+end_src

listview:
+ lines: 8
* bindings
** bindr
*** starter
#+begin_src nix :tangle default.nix
bindr = [
#+end_src

*** productivity
**** file manager
#+begin_src nix :tangle default.nix
  "$mod, N, exec, [workspace emptym] uwsm app -s a -- nautilus"
  "$mod , Y, exec, [workspace emptym] $yazi_kitty"
  # "$mod $sl, Y, exec, [workspace special:magic;float true; size 80% 80%] $yazi_kitty"
#+end_src

*** hyprpicker
#+begin_src nix :tangle default.nix
"$mod $al, H, exec, hyprpicker -an"
# "$mod $al, R, exec, \"$(hyprpicker -f rgb - | sed 's/^/(/; s/$/,1.0)/; y/ /,/\' | wl-copy -n)\""
#+end_src
*** Hyprland-easymotion

#+begin_src nix :tangle no
# default
# "$mod, z, easymotion, action:hyprctl dispatch focuswindow address:{}"

"$mod, z, easymotion, textsize:28, action:hyprctl dispatch focuswindow address:{}"
#+end_src

https://github.com/zakk4223/hyprland-easymotion

*** ghostty
#+begin_src nix :tangle default.nix
  # "$mod $al, Return, exec, $ghostty" #$terminal , wezterm, ghostty
#+end_src
*** screenshots | grimblast
using grimblast from hypr team 🤪

#+begin_src nix :tangle default.nix
  # copy save
  "$sl, Print, exec, grimblast --cursor --notify -e 2 copy output"
  ", Print, exec, grimblast --cursor --notify -e 2 copysave screen"
  # ", Scroll_Lock, exec, grimblast --cursor --notify copysave screen"

  # copy
  "SUPER, Print, exec, grimblast --cursor --notify -e 2  copysave output"
  "$al, Print, exec, grimblast --notify -e 2 copy area"
  "$cl, Print, exec, grimblast --cursor --notify -e 2 copy active"
#+end_src

*** ender
#+begin_src nix :tangle default.nix
];
#+end_src
** bind
*** starter
#+begin_src nix :tangle default.nix
bind =
  [
    # "$mod, F1,exec,  killall -9 spotify || [workspace emptym] uwsm app -- spotify"
#+end_src

*** browsers
#+begin_src nix :tangle default.nix
  "$mod , T, exec, [workspace emptym] uwsm app -s a -- freetube"
  # "$mod, C, exec, [workspace emptym] uwsm app -s a -- google-chrome-stable"
  "$mod, C, exec, [workspace emptym] uwsm app -s a -- chromium"
  "$mod, B, exec, [workspace emptym] uwsm app -s a -- qutebrowser"
  "$mod, F, exec, [workspace emptym] uwsm app -s a -- firefox"
#+end_src
*** SKUNKWORKS ☢️
**** MaluwareYt
#+begin_src nix :tangle default.nix
 # "$mod $sl, T, exec, youtubr"
 "$mod $sl, T, exec, /home/malu/.code/SkunkWorks/PySide6/youtubr/youtubr"
#+end_src
**** Ascii
#+begin_src nix :tangle default.nix
 "$mod , A, exec, ascii"
#+end_src
*** kitty
#+begin_src nix :tangle default.nix
  "$mod, Return, exec, $kitty" #$terminal , wezterm, ghostty
  "$mod $sl, Return, exec, [workspace emptym] $kitty"
#+end_src

*** pwvucontrol
#+begin_src nix :tangle default.nix
  ", XF86Tools, exec, pkill pwvucontrol ||  pwvucontrol"
#+end_src

*** rofi
#+begin_src nix :tangle default.nix
# Menu
  "$mod $cl, mouse:272, exec, pkill rofi || $menu_rofi"
  "$mod , P, exec, pkill rofi || $menu_rofi"

  # File browser
  "$mod , R, exec, pkill rofi || $file_browser_rofi"

    # Clipboard hist
  "$mod , BackSpace, exec, pkill rofi || $clip_rofi"

  # open windows
  "$mod, space, exec, pkill rofi || $rofi_open_windows"
  "$mod $cl, mouse:273, exec, pkill rofi || $rofi_open_windows"

  # power menu
  "$mod, Delete, exec, pkill rofi || rofi_power"

  # calculator
  ", XF86Calculator, exec, pkill rofi || $calc_rofi"

  # emoji
  "$mod, period, exec, pkill rofi || $emoji_rofi"
#+end_src

*** emacs
#+begin_src nix :tangle default.nix
# "$mod, D, exec, emacsclient -c -a 'emacs' %F" # launch emacs client with %F buffer?
  "$mod, E, exec, [workspace emptym] $emacs"
  "$mod $al, E, execr, notify-send 'restarting emacs' -i '/home/malu/Shibuya/assets/icons/icons8-emacs-color/icons8-emacs-48.png' ; systemctl --user restart emacs ; sleep 2 && notify-send 'restarted emacs' -i '/home/malu/Shibuya/assets/icons/icons8-emacs-color/icons8-emacs-48.png'  && $emacs"
#+end_src

*** discord
#+begin_src nix :tangle default.nix
# "$mod, D, exec, emacsclient -c -a 'emacs' %F" # launch emacs client with %F buffer?
  "$mod, D, exec, [workspace emptym] discord"
#+end_src

*** activekill
#+begin_src nix :tangle default.nix
  "$mod ,Escape, killactive"

  "$al ,F4, killactive"
  "$mod, mouse:275, killactive,"
#+end_src

*** Xtra-dispatchers
#+begin_src nix :tangle no
  "$mod $cl,Escape, plugin:xtd:closeunfocused"
  "$mod $sl, o, plugin:xtd:throwunfocused, emptym"
#+end_src

*** empty workspace, toggle floating
#+begin_src nix :tangle default.nix
  # Workspaces
  "$mod $al, Return , workspace, emptym"
  "$mod $sl, V, exec, hyprctl --batch \"dispatch togglefloating ; dispatch resizeactive exact 80% 80%;dispatch centerwindow 1;\""
  "$mod, v, togglefloating"
#+end_src

*** toggle dwindle/pseudo
#+begin_src nix :tangle default.nix
  "$mod, KP_Divide, togglesplit" # dwindle
  "$mod, KP_Multiply, pseudo"
#+end_src
*** obs
#+begin_src nix :tangle no
    "$cl $sl, R, pass, ^(com.obsproject.Studio)$"
    "$cl $sl, S, pass, ^(com.obsproject.Studio)$"
    "$cl $sl, [, pass, ^(com.obsproject.Studio)$"
    "$cl $sl, ], pass, ^(com.obsproject.Studio)$"
    "$cl $sl, \, pass, ^(com.obsproject.Studio)$"
    "$cl $sl, -, pass, ^(com.obsproject.Studio)$"
    #"$mod , comma , sendshortcut, $cl $sl, r, class:^(com\.obsproject\.Studio)$"
    #"$cl $sl, R, pass, class:^(com\.obsproject\.Studio)$"
#+end_src
*** focus favorite apps
NOTE for KP need to bind with numlock off identifier
see hyprswitch:
**** emacs
#+begin_src nix :tangle default.nix
# "$mod $cl, KP_End, focuswindow, class:^(Emacs)$"
# "$mod $cl, D, focuswindow, class:^(emacs)$"
# "$mod $cl, D, focuswindow, initialTitle:(.*)(Doom Emacs)$"
  "$mod $cl, E, focuswindow, class:^(emacs)$"
  "$mod $al, E, execr, notify-send 'restarting emacs' -i '/home/malu/Shibuya/assets/icons/icons8-emacs-color/icons8-emacs-48.png' ; systemctl --user restart emacs ; sleep 2 && notify-send 'restarted emacs' -i '/home/malu/Shibuya/assets/icons/icons8-emacs-color/icons8-emacs-48.png'  && $emacs"
#+end_src

**** discord
#+begin_src nix :tangle default.nix
"$mod $cl, D, focuswindow, class:^(discord)$"
#+end_src

**** yazi
#+begin_src nix :tangle default.nix
"$mod $cl, Y, focuswindow, title:^(Yazi)(.*)$"
  # "$mod , up, focuswindow, class:^(Emacs)$"
#+end_src
**** nautilus
#+begin_src nix :tangle default.nix
"$mod $cl, N, focuswindow, class:org.gnome.Nautilus"
  # "$mod , up, focuswindow, class:^(Emacs)$"
#+end_src
**** dolphin
#+begin_src nix :tangle no
"$mod $cl, N, focuswindow, class:org.kde.dolphin"
#+end_src
**** qutebrowser
#+begin_src nix :tangle default.nix
# "SUPER $cl, KP_Down, focuswindow, class:^(org.qutebrowser.qutebrowser)$"
# "$mod $cl, KP_Right, focuswindow, class:^(org.qutebrowser.qutebrowser)$"
"$mod $cl, B, focuswindow, class:^(org.qutebrowser.qutebrowser)$"
# "$mod , left, focuswindow, class:^(org.qutebrowser.qutebrowser)$"
#+end_src
**** chromium
#+begin_src nix :tangle default.nix
# "$mod $cl, C, focuswindow, class:^(google-chrome)$"
"$mod $cl, c, focuswindow, class:^(chromium-browser)$"
"$mod , g, exec, chromium gemini.google.com"
"$mod g, g, exec, chromium gemini.google.com"
#+end_src
**** firefox
#+begin_src nix :tangle default.nix
"$mod $cl, f, focuswindow, class:^(firefox)$"
"$mod g, f, exec, firefox gemini.google.com"
#+end_src
**** kitty
#+begin_src nix :tangle default.nix
"$mod $cl, Return, focuswindow, class:^(kitty)$"
#+end_src
**** mpv
#+begin_src nix :tangle default.nix
"$mod $cl, m, focuswindow, class:^(mpv)$"
# "$mod , down, focuswindow, class:^(mpv)$"
#+end_src
**** freetube
#+begin_src nix :tangle default.nix
"$mod $cl, T, focuswindow, class:^(FreeTube)$"
#+end_src

*** special workspaces / scratch
#+begin_src nix :tangle default.nix
"$mod, m, togglespecialworkspace, magic"
"$mod SHIFT, m, movetoworkspace, special:magic"

# "$mod, q, togglespecialworkspace, quanta"
# "$mod SHIFT, q, movetoworkspace, special:quanta"

"$mod, Next, togglespecialworkspace, easy"
"$mod SHIFT, Next, movetoworkspace, special:easy"

"$mod, i, togglespecialworkspace, nc"
#"$mod SHIFT, i, movetoworkspace, special:nc" no need to move shit into it using this for songart

"$mod, s, togglespecialworkspace, scratch"
"$mod SHIFT, S, movetoworkspace, special:scratch"

#"$mod, t, togglespecialworkspace, Tixati" #"$mod SHIFT, T, movetoworkspace, special:Tixati"
#+end_src

*** move to empty workspace
#+begin_src nix :tangle default.nix
# move to empty
  "$mod , o, movetoworkspace, emptym"
  "$mod $al, o, movetoworkspacesilent, emptym"
#+end_src

*** move focus | same workspace
#+begin_src nix :tangle default.nix
  "$mod $cl, h, movefocus, l"
  "$mod $cl, l, movefocus, r"
  "$mod $cl, k, movefocus, u"
  "$mod $cl, j, movefocus, d"
  #bind="$mod SHIFT,Left,layoutmsg,swapnext"
#+end_src

*** Group bar
#+begin_src nix :tangle default.nix
"$mod ,up, togglegroup"
  "$mod ,down, lockactivegroup, toggle"

  "$mod ,right,changegroupactive,f"
  "$mod ,left,changegroupactive,b"

  "$mod ,apostrophe,changegroupactive,f"
  "$mod ,quotedbl,changegroupactive,b"

  "$mod $sl , right, movewindoworgroup, r"
  "$mod $sl , left, movewindoworgroup, l"
#+end_src

*** workspaces
**** go/move workspace | carthage
#+begin_src nix :tangle yes
# Keypad navigation
# Switch workspaces with mod + [ numpad 0-9]
  "$mod, KP_End, focusworkspaceoncurrentmonitor, 1"#TODO: do for loop make this cleaner
  "$mod, KP_Down, focusworkspaceoncurrentmonitor, 2"
  "$mod, KP_Next, focusworkspaceoncurrentmonitor, 3"
  "$mod, KP_Left, focusworkspaceoncurrentmonitor, 4"
  "$mod, KP_Begin, focusworkspaceoncurrentmonitor, 5"
  "$mod, KP_Right, focusworkspaceoncurrentmonitor, 6"
  "$mod, KP_Home, focusworkspaceoncurrentmonitor, 7"
  "$mod, KP_Up, focusworkspaceoncurrentmonitor, 8"
  "$mod, KP_Prior, focusworkspaceoncurrentmonitor, 9"
  "$mod, KP_Insert, focusworkspaceoncurrentmonitor, 10"

  "$mod $sl, KP_End, movetoworkspace, 1"
  "$mod $sl, KP_Down, movetoworkspace, 2"
  "$mod $sl, KP_Next, movetoworkspace, 3"
  "$mod $sl, KP_Left, movetoworkspace, 4"
  "$mod $sl, KP_Begin, movetoworkspace, 5"
  "$mod $sl, KP_Right, movetoworkspace, 6"
  "$mod $sl, KP_Home, movetoworkspace, 7"
  "$mod $sl, KP_Up, movetoworkspace, 8"
  "$mod $sl, KP_Prior, movetoworkspace, 9"
  "$mod $sl, KP_Insert, movetoworkspace, 10"
#+end_src

movetoworkspacesilent exists

**** +/- workspaces, left/right workspaces | groups
#+begin_src nix :tangle default.nix
# next/prev workspace
"$mod, mouse_up, workspace, m+1"
  "$mod, mouse_down, workspace, m-1"

  "$mod ,H, workspace,m-1"
  "$mod ,L, workspace,m+1"
#+end_src

*** waybar
#+begin_src nix :tangle no
  "$mod ,Home,execr, killall -SIGUSR1 .waybar-wrapped" # toggle waybar
  # "$mod ,End,execr, killall .waybar-wrapped || uwsm app waybar"
#+end_src

*** Quickshell
#+begin_src nix :tangle default.nix
  "$mod $al,Home,execr, qs ipc call bar toggleBar"

  "$mod $al,i,execr, qs ipc call notifications dismissAll"

  "$mod $al,End,execr, systemctl --user restart quickshell"

  "$mod , Delete, execr, qs -p $XDG_CONFIG_HOME/quickshell/notBar/wlogout/shell.qml"

  "$mod $cl, KP_Left, execr, qs ipc call netspeed toggleNet"
  "$mod $cl, KP_End, execr, qs ipc call resources toggleResources"

  "$mod $al, N, execr, qs ipc call netspeed toggleNet"
  "$mod $al, R, execr, qs ipc call resources toggleResources"

    # Playing | Mpris
  "$mod, F7, execr, qs ipc call mprisTog toggleMpris"
  "$mod $al, F7, execr, qs ipc call mprisTog toggleMprisIcon"
  "$mod $sl, F7, execr, qs ipc call mpris raise"

  ", F8, execr, qs ipc call mpris next"
  ", F6, execr, qs ipc call mpris previous"
  ", F7, execr, qs ipc call mprisTog togglePlaying"
#+end_src

*** swap position in workspace clockwise
#+begin_src nix :tangle default.nix
  "$mod $sl, semicolon, swapnext"
  # "$mod , Up, exec, hyprctl --batch \"dispatch swapactiveworkspaces HDMI-A-1 $( hyprctl monitors | grep DP | cut -d ' ' -f2 ) ; dispatch focusmonitor +1;\""
#+end_src

*** focus previously focused window, cycle next, previous_per_monitor
#+begin_src nix :tangle default.nix
# "$mod,K, Workspace, previous_per_monitor"
  "$mod,K, focuscurrentorlast"
  "$mod $sl, k, focusmonitor, +1"
  "$mod, mouse:276, Workspace, previous_per_monitor"
  "$mod, semicolon, cyclenext"
]
#+end_src

*** workspaces 1-10 with home row
#+begin_src nix :tangle default.nix
++ (
  builtins.concatLists (builtins.genList ( i:
      let
        ws = i + 1;
      in
        [
          "$mod, code:1${toString i}, workspace, ${toString ws}"
          "$mod SHIFT, code:1${toString i}, movetoworkspace, ${toString ws}" # this is genius 1-10, amazing
        ]
    ) 9
  )
)
#+end_src
*** Tangier-Carthage-bind
#+begin_src nix :tangle yes
++ (if osConfig.networking.hostName == "tangier" then []
  else [

    # "$mod ,bracketleft, movecurrentworkspacetomonitor, 0" # DP-3
    # "$mod ,bracketright, movecurrentworkspacetomonitor, 1" # HDMI-A-1

    "$mod ,bracketleft, movewindow, mon:0"
    "$mod ,bracketright, movewindow, mon:1"

    "$mod $cl,bracketleft, movewindow, mon:0 silent"
    "$mod $cl,bracketright, movewindow, mon:1 silent"

    "$mod $sl, bracketright, execr, hyprctl dispatch -- swapactiveworkspaces HDMI-A-1 $(hyprctl monitors | awk '/^Monitor DP/ {print $2}')"
    "$mod $sl, bracketleft, execr, hyprctl --batch \"dispatch swapactiveworkspaces HDMI-A-1 $(hyprctl monitors | awk '/^Monitor DP/ {print $2}'); dispatch focusmonitor +1;\""
  ]);
#+end_src

** bindm/c ( mouse binding )
|--------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------|
| Name         | Description               | Params                                                                                                                                   |
|--------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------|
| movewindow   | moves the active window   | none                                                                                                                                     |
| resizewindow | resizes the active window | 1 - resize and keep window aspect ratio, 2 - resize and ignore keepaspectratio window rule/prop, none or anything else for normal resize |
|--------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------|
LMB -> 272
RMB -> 273

#+begin_src nix :tangle default.nix
#mouse binds have one less arg
bindm = [
  "$mod , mouse:272, movewindow"
  # "$mod , mouse:272, pass, class:^(dota2)$"
  "$mod , mouse:273, resizewindow" # 1 - keep aspect ratio, 2 - ignore aspect
  # "ALT, mouse:272, movewindow"
];

bindc = [
  # "ALT, mouse:272, togglefloating"
];
#+end_src

** bindl
#+begin_src nix :tangle default.nix
bindel =
  [
    ", XF86AudioPlay, execr, pause_play"
    # mute
    ", XF86AudioMute, execr, volume_dunst toggle_mute"

    # "$mod, F12, execr, volume_dunst earphones"
    # "$mod, F11, execr, volume_dunst speaker"
    # "$mod, F10, execr, volume_dunst bluetooth"

    # ", XF86AudioRaiseVolume, execr, volume_dunst 2%+"
    # ", XF86AudioLowerVolume, execr, volume_dunst 2%-"

    ", XF86AudioRaiseVolume, execr, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 2%+ >/dev/null 2>&1 "
    ", XF86AudioLowerVolume, execr, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 2%- >/dev/null 2>&1 "

    # ", XF86AudioNext, execr, playerctl -p spotify next || playerctl next " # TODO test for spotify running
    ", XF86AudioNext, execr, qs ipc call mpris next" # TODO test for spotify running
    ", XF86AudioPrev, execr, qs ipc call mpris previous"
    ", XF86AudioPlay, execr, qs ipc call mprisTog togglePlaying"
   ];
#+end_src

** binde
[[file:~/Shibuya/modules/home/hyprland-helper/scripts/gaps.nix][The gaps script]]

#+begin_src nix :tangle default.nix
binde =
  [# Date
    "$mod, Prior, execr, ${pkgs.libnotify}/bin/notify-send -r 20 -i '/home/malu/Shibuya/assets/icons/icons8-stopwatch-office-l/icons8-stopwatch-30.png'  \"$date_short  \" ; ${pkgs.libcanberra-gtk3}/bin/canberra-gtk-play -i message"
    "$mod $sl, Prior, execr, ${pkgs.libnotify}/bin/notify-send -r 20 -i '/home/malu/Shibuya/assets/icons/icons8-today-windows-11-color/icons8-today-30.png' \"$date_long  \" ; ${pkgs.libcanberra-gtk3}/bin/canberra-gtk-play -i message"

    "$mod, backslash, execr, ${pkgs.libnotify}/bin/notify-send -r 20 -i '/home/malu/Shibuya/assets/icons/icons8-stopwatch-office-l/icons8-stopwatch-30.png'  \"$date_short  \" ; ${pkgs.libcanberra-gtk3}/bin/canberra-gtk-play -i message"
    "$mod $sl, backslash, execr, ${pkgs.libnotify}/bin/notify-send -r 20 -i '/home/malu/Shibuya/assets/icons/icons8-today-windows-11-color/icons8-today-30.png' \"$date_long  \" ; ${pkgs.libcanberra-gtk3}/bin/canberra-gtk-play -i message"
  ]
  ++[
    "$mod $sl,i,execr, songart"
    ", Pause, execr, songart"
  ]++
  [
    #GAPS
    "$mod ,KP_Enter, exec, gaps reset_zero" # set according to hyprland config default

    # increase/decrease gaps
    "$mod,KP_Add, exec, gaps increment_gap"
    "$mod,KP_Subtract, exec, gaps decrease_gap"

    "$mod $al, KP_Enter, exec, gaps gaps_in_reset"
    "$mod $al, KP_Add, exec, gaps gaps_in_add"
    "$mod $al, KP_Subtract, exec, gaps gaps_in_sub"

    "$mod ,KP_Enter, exec, gaps reset_config"
    "$mod ,$ar, exec, gaps toggle_gaps_out"# gaps on/off
  ];
};
 };
}
#+end_src
** notes
*** multiple binds to one key
# to switch between windows in a floating workspace
bind = SUPER, Tab, cyclenext,           # change focus to another window
bind = SUPER, Tab, bringactivetotop,    # bring it to the top

*** bind flags
|------+-----------------------------------------------+------------------------------------------------------------------------------------------------|
| flag | use case                                      | extra                                                                                          |
|------+-----------------------------------------------+------------------------------------------------------------------------------------------------|
| l    | locked                                        | will aso when when an input inhibitor is active. eg lockscreen                                 |
| r    | release                                       | trigger on release of a key                                                                    |
| o    | longPress                                     | trigger on longpress                                                                           |
| e    | repeat                                        | repeat when held                                                                               |
| n    | non-consuming                                 | key/mouse events will be passed to the active window in addition to triggering the dispatcher. |
| m    | mouse                                         |                                                                                                |
| t    | transparent                                   | cannot be shadowed by other binds                                                              |
| i    | ignore mods                                   | will ignore modifiers                                                                          |
| s    | seperate                                      | will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above. |
| d    | has description                               |                                                                                                |
| p    | bypass the app's requests to inhibit keybinds |                                                                                                |
|      |                                               |                                                                                                |
|------+-----------------------------------------------+------------------------------------------------------------------------------------------------|
=c= -> click, will trigger on release of a key or button as long as the mouse cursor stays inside binds:drag_threshold.
=g= -> drag, will trigger on release of a key or button as long as the mouse cursor moves outside binds:drag_threshold.

*** Description to keybindings
You can describe your keybind with the description flag. Your description always goes in front of the dispatcher and should never contain the character ,!

bindd = MODS, key, description, dispatcher, params

for example,

#+begin_quote
bindd = SUPER, Q, Open my favourite terminal, exec, kitty
#+end_quote

If you want to access your description you can use hyprctl binds. For more information have a look at Using Hyprctl.

