#+title: Themes
#+auto_tangle: t
#+startup: content indent

* start / hyprland condition
#+begin_src nix :tangle themes.nix
{pkgs, osConfig, lib, config, ...}:

# let
#   gruvboxplus = import ../home/gruvbox-plus.nix { inherit pkgs;};
# in
# lib.mkIf osConfig.services.desktopManager.plasma6.enable {
lib.mkIf osConfig.hyprland.enable {
#+end_src

* home
#+begin_src nix themes.nix
home.pointerCursor = {
  enable = true; # false::
  gtk.enable = true; # waybar, gtk apps
  hyprcursor = {
    size = 24; # 32::
    enable = true;
  };
  x11 = {
    enable = true; # false:: xwayland?
    # defaultCursor = pkgs.
  };
  name = "Bibata-Modern-Ice";
  package = pkgs.bibata-cursors;
  size = if osConfig.networking.hostName == "carthage" then 24 else if osConfig.networking.hostName == "tangier" then 20 else 18;
};
#+end_src

* gtk applications
** start
#+begin_src nix :tangle themes.nix
gtk = {
  enable = true;
  #font = {
  #name = "DaddyTimeMono Nerd Font";
  #size = 12;
  #};
#+end_src

** waybar?, gtk apps cursor
*** cursor theme
#+begin_src nix :tangle themes.nix
cursorTheme = {
  package = pkgs.bibata-cursors; name = "Bibata-Modern-Ice";
  size = if osConfig.networking.hostName == "carthage" then 24 else if osConfig.networking.hostName == "tangier" then 20 else 18;
};#NOTE: not needed?
#+end_src

*** nautilus etc theme, gtk theme + icons
#+begin_src nix :tangle themes.nix
theme = {
  name = "Nightfox-Dark";
  package = pkgs.nightfox-gtk-theme;
  # name = "tokyonight-gtk-theme"; package = pkgs.Tokyonight-Moon;
};

iconTheme = {
  # package = pkgs.kora-icon-theme; name = "kora-icon-theme";
  package = pkgs.candy-icons; name = "candy-icons";
  # package = pkgs.windows10-icons; name = "windows10-icons";
  # package = pkgs.gruvbox-plus-icons;
  # name = "gruvbox-plus-icons";
};
#+end_src

+ gtk.iconTheme.name
    The name of the icon theme within the package
+ gtk.iconTheme.package
    Package providing the icon theme

** gtk2, gtk3, gtk4 start
#+begin_src nix :tangle themes.nix
gtk2 = {
  extraConfig = ''
        "gtk-can-change-accels" = "1"
      '';
  configLocation = "${config.xdg.configHome}/gtk-2.0/gtkrc"; #FIXME not working?
};

gtk3 = {
  extraConfig = {
    gtk-application-prefer-dark-theme = 1;
  };
  # bookmarks = [ #FIXME error
  #   "file://home/malu/org"
  # ];
};

gtk4 = {
  # extraCss = '''';
  extraConfig = {
    #     #gtk-theme-name = ''Nightfox:Dark''; #eg nautilus
    #     gtk-theme-name = "Nightfox-Dark"; #eg nautilus
    #     gtk-cursor-blink = false;
    gtk-recent-files-limit = 20;
    gtk-application-prefer-dark-theme = 1;
  };
  #   # extraCss = #gtk-4.0/gtk.css
  #   #   ''
  #   # '';
};
#+end_src

** end
#+begin_src nix :tangle themes.nix
};
#+end_src

* qt
#+begin_src nix :tangle themes.nix
qt = {
  enable = true;
  platformTheme.name = "adwaita-dark"; #kvantum , gtk, gnome, kde, gtk3, **deprecated
  # platformTheme.name = "qtct"; # "gtk", "gtk3", "gnome", "adwaita", "lxqt", "qtct", "kde" or (submodule) #qt6ct
  # platformTheme = "gnome";
  style.name = "adwaita-dark";
};
#+end_src

** =qt.style.name=
Style to use for =Qt5/Qt6= applications. Case-insensitive.

Some examples are:
- =adwaita,= adwaita-dark, adwaita-highcontrast, adwaita-highcontrastinverse : Use the Adwaita style from [[github:FedoraQt/adwaita-qt][adwaita-qt]]
- =breeze= : Use the Breeze style from =breeze=
- bb10bright, bb10dark, cde, cleanlooks, gtk2, motif, plastique : Use styles from =qtstyleplugins=
- =kvantum= : Use styles from =kvantum.=

** =qt.platformTheme=
Selects the platform theme to use for Qt applications.
The options are:
- =gnome=: Use GNOME theme with qgnomeplatform
- =gtk2=: Use GTK theme with qtstyleplugins
- =kde=: Use Qt settings from Plasma.
- =lxqt=: Use LXQt style set using the lxqt-config-appearance application.
- =qt5ct=: Use Qt style set using the qt5ct and qt6ct applications.

** =qt.style=
Selects the style to use for Qt applications.
The options are:
- =adwaita=, adwaita-dark, adwaita-highcontrast, adawaita-highcontrastinverse: Use Adwaita Qt style with adwaita
- =breeze=: Use the Breeze style from breeze
- bb10bright, bb10dark, cleanlooks, gtk2, motif, plastique: Use styles from qtstyleplugins
- =kvantum=: Use styles from kvantum.

  =NOTE= platformTheme: gnome deprecated use 'adwaita'
* missing adwaita thems
* end
#+begin_src nix :tangle themes.nix
}
#+end_src
