#+auto_tangle: t
#+startup: content

* header
#+begin_src nix :tangle default.nix
{config, modulesPath, lib, pkgs, ...}:
{
#+end_src
* imports
#+begin_src nix :tangle default.nix
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../modules/nix
    ./users
    ./storage-common.nix
    ./specialisations
  ];
#+end_src
* allow unfree
#+begin_src nix :tangle default.nix
  nixpkgs.config = {
    allowUnfreePredicate =
      pkg:
      builtins.elem (lib.getName pkg) [
        "broadcom-sta"
        # "ciscoPacketTracer8"
        "n8n"
        # "android-studio-stable"
        "steam-unwrapped"
        "nvidia-x11"
        "xone-dongle-firmware"
        "steam"
        "nvidia-x11-570.153.02-6.12.30"
        "nvidia-settings"
      ];
    permittedInsecurePackages = [
      "broadcom-sta-6.30.223.271-59-6.12.68"
      # "libxml2-2.13.8" # for cisco?
    ];
  };
#+end_src

* boot
#+begin_src nix :tangle default.nix
  boot = {
    plymouth.enable = false;
    extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
    loader = {
      systemd-boot = {
        enable = true;
        # editor = false; # true:: allow editing kernel commandline before boot
        # windows
        # sortKey = "nixos"; #https://uapi-group.org/specifications/specs/boot_loader_specification/#sorting
      };
      efi.canTouchEfiVariables = true;
      timeout = 2;
    };
    initrd.kernelModules =
      if config.networking.hostName == "carthage" then
        [
          # "dm-snapshot"               # lvm
          # "amdgpu"
        ]
      else
        [ ];
    initrd.availableKernelModules =
      if config.networking.hostName == "carthage" then
        [
          "nvme"
          "xhci_pci"
          "ahci"
          "usbhid"
          "usb_storage"
          "sd_mod"
        ]
      else
        [
          "xhci_pci" # usb 3.0
          "ehci_pci" # usb 2.0
          "ahci" # sata
          "usb_storage" # usb mass storage devices - hdd, flash
          "sd_mod" # scsi device and some sata
          "sr_mod" # cd drive
        ];
    initrd.systemd.network = {
      enable = false;
      wait-online.enable = false; # since using networkmanager not networkd;
    };
    kernelModules =
      if config.networking.hostName == "tangier" then
        [
          "kvm-intel"
          "wl"
        ]
      else
        [
          "kvm-amd"
          "wl" # broadcomm closed source
        ];
    kernelParams = [# parameterrs for kernel command line
    #   "video=HDMI-A-1:1920x1080@240"
    #   "video=DP-3:1920x1080@60"
      "nohibernate" # because zfs
    ];
    # supportedFilesystems = { ntfs-3g = true; ext4 = true; }; # can also be list # supportedFilesystems = [ "ntfs" ];
  };
#+end_src

https://search.nixos.org/options?channel=25.05&show=boot.loader.systemd-boot.sortKey&from=0&size=50&sort=relevance&type=packages&query=boot.loader.systemd

* services - libinput , zfs
#+begin_src nix :tangle default.nix
  services = {
    libinput.enable = lib.mkIf (config.networking.hostName == "tangier") true; # touchpad, should be on by default
    zfs = {
      autoSnapshot.enable = true; # TODO: see sanoid in man configuration.nix
      autoScrub.enable = true;
      trim.enable = true; # true:: - zpool trim, different from autorim pool property
    };
  };
#+end_src

* usb storage gracefull powr off
#+begin_src nix :tangle default.nix
  hardware.usbStorage.manageShutdown = true;
#+end_src

* networking stuffs
** start
#+begin_src nix :tangle default.nix
  programs.nm-applet.enable = lib.mkIf config.hyprland.enable true; # started automatically with the graphical session
  programs.nm-applet.indicator = lib.mkIf config.hyprland.enable true;

  networking = {
#+end_src

** wireless | wpa_supplicant
#+begin_src nix :tangle no
    wireless = {
      enable = true;
      userControlled.enable = true; # wpa_supplicant_gui
      networks = {
        Measles = {
          psk = "vaccinate";
        };
        "4g+" = {
          psk = "abdc1234!@";
        };
        # free.wifi = { }; # Public wireless network
      };
    };
#+end_src

** networkmanager
#+begin_src nix :tangle default.nix
  networkmanager = {
    enable = true; # add user to group
    dns = "none"; # dnsmasq, default::, systemd-resolved
    wifi = {
      powersave = false; # TODO what it does
      # backend = "wpa_supplicant"; # wpa_supplicant::, iwd
    };
    logLevel = "WARN"; # "OFF", "ERR", "WARN"::, "INFO", "DEBUG", "TRACE"
    unmanaged = [
      # "*"
      # "except:type:wwan"
      # "except:type:gsm"
    ];
  };
#+end_src

DNS = "none" # Disable NetworkManager's internal DNS resolution
** modemmanager
#+begin_src nix :tangle default.nix
  modemmanager = {
    enable = true;
  };
#+end_src

fccUnlockScripts: List of FCC unlock scripts to enable on the system, behaving as described in https://modemmanager.org/docs/modemmanager/fcc-unlock/#integration-with-third-party-fcc-unlock-tools.
example:
#+begin_src nix
[{ id = "03f0:4e1d"; path = "${pkgs.modemmanager}/share/ModemManager/fcc-unlock.available.d/03f0:4e1d"; }]
#+end_src

** time servers
#+begin_src nix :tangle default.nix
  timeServers = [
    "0.nixos.pool.ntp.org"
    "1.nixos.pool.ntp.org"
    "2.nixos.pool.ntp.org"
    "3.nixos.pool.ntp.org"
  ];
#+end_src

** dhcp

useDHCP: Whether to use DHCP to obtain an IP address and other configuration for all network interfaces that do not have any manually configured IPv4 addresses.

Not needed when managing dns ourselves 😄

#+begin_src nix :tangle default.nix
# dhcpcd.enable = true; # true::
# useDHCP =  false;
# interfaces.enp5s0.useDHCP = if config.networking.hostName == "carthage" then true else false; #overrides default in useDHCP unless null
# interfaces.wlo1.useDHCP = if config.networking.hostName == "tangier" then true else false;

# Manual DNS config
nameservers = [ "1.1.1.1" "1.0.0.1"  "8.8.8.8" "8.8.4.4" ];
#+end_src

use ~ip link~ to see all available interfaces

# Enables DHCP on each ethernet and wireless interface. In case of scripted networking  (the default) this is the recommended approach.
# When using systemd-networkd it's
# still possible to use this option, but it's recommended to use it in conjunction
# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
** end
#+begin_src nix :tangle default.nix
};
#+end_src
** DONE investigate issue with school wpa
CLOSED: [2025-12-25 Thu 07:48]
Forget everything...relog in from step 1
* hardware
=Technologies=
- (A2DP - high , HSP/HFP-telephone - low,) older,
- hsphfpd -middleman -> Better mic (NOTE: cannot be used with wireplumber)

better mic zoom,discord with hsphfpd

NOTE: for bt to work in HSP/HFP mode, test further

#+begin_src nix :tangle default.nix
hardware = {
  # enableAllFirmware = true; # enable all firmware regardless of license 
  # enableAllHardware = true; # Enable support for most hardware
  enableRedistributableFirmware = true; # enable firmware with a license allowing redistribution
  bluetooth = {
    # hsphfpd.enable = true; # support for hsphfpd[-prototype] implementation.
    enable =  true;
    powerOnBoot = true; #power on default controller on boot
    settings = {#Set configuration for system-wide bluetooth (/etc/bluetooth/main.conf). See https://github.com/bluez/bluez/blob/master/src/main.conf for full list of options.
      General = {
        Experimental = true; #battery %
        # ControllerMode = "bredr";
      };
    };
    # package = pkgs.bluez;
    # network = {
    #     General = {
    #       DisableSecurity = false; # Disable link encryption: default=false
    #     };
    # };
    input = {#Set configuration for the input service (/etc/bluetooth/input.conf). See https://github.com/bluez/bluez/blob/master/profiles/input/input.conf for full list of options.
      General = {
      # ClassicBondedOnly = false; #true:: # # Limit HID connections to bonded devices
      IdleTimeout = 30;# 0 (disabled)::
      #UserspaceHID=true; #true:: # # Enable HID protocol handling in userspace input profile - true,false, persist
      #LEAutoSecurity=true; # true::
      };
    };
  };
};

# users.groups.students.gid = 1000; # creates group called students, gid optional
#+end_src

* security, rtkit, sudo, polkit
** start
#+begin_src nix :tangle default.nix
# config= lib.mkIf (config.specialisation != {}) {
security = {
  rtkit.enable = true; # pipewire need?
#+end_src

** sudo
security.sudo.extraRules/`security.sudo.configFile`
#+begin_src nix :tangle default.nix
sudo = {
  enable = true;
  extraRules = [
    { commands = [
      #{
      #command = "${pkgs.systemd}/bin/systemctl suspend";
      #options = [ "NOPASSWD" ];
      #}

      # {
        # command = "/run/current-system/sw/bin/nixos-rebuild";
      #   command = "${pkgs.nixos-rebuild}/bin/nixos-rebuild";
      #   options = [ "NOPASSWD" ];
      # }

      #{
      #command = "${pkgs.systemd}/bin/reboot";
      #options = [ "NOPASSWD" ];
      #}
      #{
      #command = "${pkgs.systemd}/bin/poweroff";
      #options = [ "NOPASSWD" ];
      #}
      {
        command = "${pkgs.util-linux}/bin/fdisk -l";
        options = [ "SETENV" "NOPASSWD" ];
      }
    ];
    # groups = [ "wheel" ];
    users = ["malu"];
  }
  ];
};
#+end_src

** polkit
*** start
#+begin_src nix :tangle default.nix
polkit = {
  enable = true;
#+end_src

*** extraconfig
**** start
#+begin_src nix :tangle default.nix
extraConfig = ''
#+end_src

**** reboot/poweroff for non sudo users
#+begin_src nix :tangle default.nix
polkit.addRule(function(action, subject) {
  if (
    subject.isInGroup("users")
    && (
      action.id == "org.freedesktop.login1.reboot" ||
      action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
      action.id == "org.freedesktop.login1.power-off" ||
      action.id == "org.freedesktop.login1.power-off-multiple-sessions"
    )
  )
    {
      return polkit.Result.YES;
    }
});
#+end_src

**** blueman
#+begin_src nix :tangle default.nix
polkit.addRule(function(action, subject) {
  if ((action.id == "org.blueman.network.setup" ||
       action.id == "org.blueman.dhcp.client" ||
       action.id == "org.blueman.rfkill.setstate" ||
       action.id == "org.blueman.pppd.pppconnect") &&
  subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
#+end_src

**** end
#+begin_src nix :tangle default.nix
'';
#+end_src

*** end
#+begin_src nix :tangle default.nix
};
#+end_src

** end
#+begin_src nix :tangle default.nix
}; # end of security
#+end_src

* nix settings
** nix optimise
#+begin_src nix :tangle default.nix
# Automatically run the nix store optimiser at a specific time.
nix.optimise = {
  automatic = true; # false::
  dates = ["weekly"];
  #dates = ["03:15" "00:00"]; # see systemd.time(7) for specification
  randomizedDelaySec = "30min"; # 1800:: systemd.time(7)
  # persistent = false; # true::
};

nix.settings.auto-optimise-store = true;#optimise with everybuild nix-store --optimise (manual) # Nix automatically detects files in the store that have identical contents, and replaces them with hard links to a single copy. #false::
#+end_src
** nix garbage collector
#+begin_src nix :tangle default.nix
nix.gc = {
  automatic = true;
  dates = "weekly"; # "03:15";
  options = "--delete-older-than 14d";
  # randomizedDelaySec = "30min"; # 1800:: systemd.time(7)
  # persistent = false; # true::
};
#+end_src
** nix settings
#+begin_src nix :tangle default.nix
nix.settings = {
  # warn-dirty = false;
  allowed-users = [             # Allowed to connect with the nix daemon. All users with *:: Trusted users always allowed to connect
    "@wheel"
    "malu"
    "@darth"
    "sumbi"
  ];
  trusted-users = [ # have additional rights when connecting to nix daemon. specify additional binary caches, or to import unsigned NARs
    # "remotebuild"
    # "remotebuild"
    # "@remotebuild"
    "malu"
  ];
  extra-sandbox-paths = [ config.programs.ccache.cacheDir ];
  experimental-features = [ "nix-command" "flakes" ];
  substituters = [
    # "https://cache.nixos.org?priority=10"
    "https://hyprland.cachix.org"
    "https://nix-community.cachix.org"
    "https://yazi.cachix.org"
    # "https://konradmalik.cachix.org"
    #"https://cache.nixos.org" #used automatically by nix pkg mgr
  ];
  trusted-public-keys = [
    # "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    "hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="
    "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    "yazi.cachix.org-1:Dcdz63NZKfvUCbDGngQDAZq6kOroIrFoyO064uvLh8k="
    #"cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    # "konradmalik.cachix.org-1:9REXmCYRwPNL0kAB0IMeTxnMB1Gl9VY5I8w7UVBTtSI="
  ];
};
#+end_src

** nix extra options
*** start
#+begin_src nix :tangle no
extraOptions = ''
#+end_src

*** FIXME offline builds
NOTE OBSOLETE
#+begin_src nix :tangle no
keep-outputs = true;
keep-derivations = true; # keep build-time dependencies around/be able to rebuild while being offline
#+end_src
*** end
#+begin_src nix :tangle no
'';
#+end_src

* locale settings
#+begin_src nix :tangle default.nix
i18n = {
  defaultLocale = "en_US.UTF-8";
  extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };
};
#+end_src

* timezone
#+begin_src nix :tangle default.nix
time.timeZone = "Africa/Nairobi";
#+end_src
* hostPlatform
#+begin_src nix :tangle default.nix
nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; # ignored with nixpkgs.pkgs set
#+end_src

* system.stateVersion -- NOTE dont delete/change
#+begin_src nix :tangle default.nix
system.stateVersion = if config.networking.hostName == "tangier" then "24.11" else "25.11";
#+end_src

* Ender
#+begin_src nix :tangle default.nix
}
#+end_src
