#+title: my ncmpcpp master config
#+auto_tangle: t
#+startup: content indent

* start
#+begin_src nix :tangle default.nix
{
  programs.ncmpcpp = {
    enable = true;
    # package = pkgs.ncmpcpp.override { visualizerSupport = true; };
#+end_src

* music location
#+begin_src nix :tangle default.nix
    mpdMusicDir = "~/Music";
#+end_src

* bindings
#+begin_src nix :tangle default.nix
bindings = [
# scroll
{ key = "j";command = "scroll_down";}

{ key = "k"; command = "scroll_up"; }

{key = "l"; command = "next_column";}

{key = "L";command = "next_screen";}

{ key = "H"; command = "previous_screen"; }

{ key = "h"; command = "previous_column"; }

{ key = "shift-tab"; command = "previous"; }

{ key = "tab"; command = "next"; }

##lyrics
{ key = "'";  command = "show_lyrics"; }

{ key = "^"; command = "toggle_lyrics_fetcher"; }

# playlists manipulation
{ key = "J"; command = [ "select_item" "scroll_down" ]; }

#{ key = "ctrl-v"; command = "select_range"; }

# WARN: DANGEROUS
{ key = "d"; command = "delete_browser_items"; }

{
  key = "K";
  command = [
    "select_item"
    "scroll_up"
  ];
}

];
#+end_src

** docs
*** to bind
Because each action has runtime checks whether it's ok to run it, a few actions can be bound to one key.

Actions will be bound in order given in configuration file. When a key is pressed, first action in order will test itself whether it's possible to run it.

If test succeeds, action is executed and other actions bound to this key are ignored.

If it doesn't, next action in order tests itself etc.

*** unbind default bindings
When ncmpcpp starts, bindings configuration file is parsed and then ncmpcpp provides "missing pieces" of default keybindings.

If you want to disable some bindings, there is a special action called 'dummy' for that purpose.

Eg. if you want to disable ability to crop playlists, you need to put the following into configuration file:
#+begin_src
def_key "C"
  dummy
#+end_src

After that ncmpcpp will not bind any default action
to this key.
*** macros

=push_character= "character" - pushes given special character into input queue, so it will be immediately picked by ncmpcpp upon next call to readKey function.
  + This action simulates pressing a specific key.
  + The "character" argument is a string representing the key you want to simulate.
  + When this action is executed within a macro, the specified key press is added to ncmpcpp's input queue. The next time ncmpcpp expects user input (through its readKey function), it will see this pushed character as if the user actually typed it.
  + The list of Accepted values shows the special keys that can be simulated. These include basic navigation keys (up, down, left, right), editing keys (delete, insert, backspace), control keys (ctrl-a to ctrl-_), function keys (f1 to f12), and even "mouse" events.
  + The note about alt-/ctrl-/shift- prefixes means you can simulate key combinations like alt-left, ctrl-f9, or shift-tab.

 =push_characters= "string" - pushes given string into input queue.
 + Similar to push_character, but this action allows you to push an entire string of characters into the input queue.
 + This is useful for automating sequences of typing, like entering a specific filter or command.

=require_runnable= "action" - checks whether given action is runnable and fails if it isn't.
+ This action adds a condition to your macro.
+ It checks if the specified "action" (another ncmpcpp command) can be executed in the current context.
+ If the "action" cannot be run (e.g., trying to apply a filter when there's no playlist), the entire macro execution is stopped, preventing the subsequent actions from running.
+ The example illustrates the importance of require_runnable. Without it, if apply_filter couldn't run, the characters "custom_filter" would be left in the input queue, potentially triggering unintended ncmpcpp actions ('c' clearing the playlist, 'u' updating the database, etc.). By using require_runnable "apply_filter" first, the macro ensures that "custom_filter" is only pushed if apply_filter can actually be executed.

=require_screen= "screen" - checks whether given screen is currently active.
+ This action checks if ncmpcpp is currently displaying a specific screen.
+ The "screen" argument must be one of the accepted values, which are the names of different ncmpcpp interfaces (e.g., browser for the file browser, playlist for the current playlist, tag_editor for editing song tags).
+ If the specified screen is not active, the macro execution is aborted. This allows you to create macros that only work within a specific context.

=run_external_command= "command" - runs given command using =system()= function.
+ This action executes a shell command outside of ncmpcpp using the standard C library function system().
+ The "command" argument is the string representing the shell command you want to run.
+ Be cautious when using this, as it can have security implications if the command or its arguments are not carefully controlled.

=run_external_console_command= "command" - runs given console command using system() function.
+ This action seems to be very similar to run_external_command. It also executes a shell command using system().
+ The distinction between "command" and "console command" might relate to how ncmpcpp handles the output or context of the executed command, but the documentation here doesn't explicitly detail the difference.

In addition to binding to a key, you can also bind actions or chains of actions to a command.

This section explains that you can also define custom commands in ncmpcpp, similar to how you define keybindings.

def_command "quit" [deferred]
  *stop*
  *quit*

+ This defines a new command named "quit".
+ The actions stop (stop playback) and quit (exit ncmpcpp) are associated with this command.
+ The [deferred] keyword in square brackets specifies how the command is executed. deferred means that after you type the command "quit" and press enter, ncmpcpp will wait for another confirmation (pressing enter again) before actually executing the stop and quit actions.

NOTE: while command chains are executed, internal environment update (which includes current window refresh and mpd status update) is not performed for performance reasons.

During the execution of a sequence of actions within a custom command, ncmpcpp generally doesn't update its display or the status from MPD in between each action to improve performance.
However, it may be desirable to do so in some situtation. Therefore it's possible to invoke by hand by performing 'update enviroment' action.
If you need ncmpcpp to refresh its display or update its MPD status within a command chain, you can explicitly include the 'update enviroment' action in your command definition.

*** default bindings file
[[file:bindings]]
* settings
#+begin_src nix :tangle default.nix
settings = {
#+end_src

** start up
display_screens_numbers_on_start = true; not working

#+begin_src nix :tangle default.nix
startup_screen = "playlist";
user_interface = "classic"; # classic , alternative #TODO: add snippet for nice comments
default_place_to_search_in = "database"; #playlist
#+end_src

** pop up , messages
#+begin_src nix :tangle default.nix
message_delay_time = 2;
connected_message_on_startup = false;
#+end_src

** screen switch
If set to "previous", key_screen_switcher will switch between current and last used screen. If set to "sequence: user_defined_sequence", it will switch between given sequence of screens. Syntax clarification can be found in example config file.

#+begin_src :tangle default.nix
screen_switcher_mode = "previous";
#+end_src

** locked screen part
If enabled, ncmpcpp will ask for % of locked screen's width each time you want to lock a screen. If you disable that, it'll silently attempt to use default value.

#+begin_src nix :tangle default.nix
locked_screen_width_part = "50"; # 20-80::
ask_for_locked_screen_width_part = true; # disable to use default
#+end_src

#+begin_src nix :tangle default.nix
jump_to_now_playing_song_at_start = true;
#now_playing_prefix = " "; # 󱉺  
now_playing_prefix = "  ";#TODO:check how to filter out songs from playlist
now_playing_suffix = "  ";
#+end_src

** external editor
#+begin_src nix :tangle default.nix
external_editor = "/home/malu/.nix-profile/bin/emacsclient -nc";
use_console_editor = true;#TODO: what is sit doing?
#+end_src

** cursor position
#+begin_src nix :tangle default.nix
# functionality
centered_cursor = true; #playing focus
autocenter_mode = true; # Centers highlight on current song during switch


#+end_src


+ centered_cursor = yes/no
        If enabled, currently highlighted position in the list will be always centered.

+ autocenter_mode = yes/no
        Default state for autocenter mode at start.
** misc
#+begin_src nix :tangle default.nix
block_search_constraints_change_if_items_found = true; # fields in Search engine above "Reset" will be blocked after successful searching

cyclic_scrolling = true;

display_bitrate = false;

enable_window_title = true;

ignore_diacritics = true; # local language ^ pronounciation marker eg. shadda, umlauts TODO : investigate if this is what is causing issues with -

ignore_leading_the = true;
#+end_src
** tags
#+begin_src nix :tangle default.nix
tag_editor_extended_numeration = true;
empty_tag_marker = "*empty*";
#empty_tag_color = "";
#+end_src

** media library
media_library_left_column = "a";#a/y/g/c/p - not work
 
#+begin_src nix :tangle default.nix
media_library_primary_tag = "album_artist"; #album_artist, artist, date, genre, composer, performer
media_library_albums_split_by_date = true;
media_library_hide_album_dates = true;
# media_library_disable_two_column_mode = false; # false::
#+end_src

** find
#+begin_src nix :tangle default.nix
default_find_mode = "wrapped"; #wrapped - go to match as you type, normal <key>w

#+end_src

** lyrics
#+begin_src nix :tangle default.nix
lyrics_directory = "~/Music/lyrics";
store_lyrics_in_song_dir = false;
fetch_lyrics_for_current_song_in_background = false;

# lyrics_fetchers = "genius , azlyrics";
lyrics_fetchers = "genius";
# lyrics
follow_now_playing_lyrics = true;
# lyrics_directory = "~/.local/share/darth_ncmpcpp";
#+end_src

** seeking
#+begin_src nix :tangle default.nix
incremental_seeking = "yes";
seek_time = "1";
#+end_src

** title
If enabled, column titles will be displayed, otherwise hidden.

#+begin_src nix :tangle default.nix
titles_visibility = false;
#+end_src

** header
#+begin_src nix :tangle default.nix
header_text_scrolling = true;
header_visibility = true; # If enabled, header window will be displayed, otherwise hidden.
header_window_color = 136; # page title #holy purplee
#+end_src

** colors | list format
*** color1, color2
One of colors used in Song info, Tiny tag editor and Search engine.

#+begin_src nix :tangle default.nix
color1 = 112;
color2 = 136;
#+end_src

*** list/column format
**** column list
#+begin_src nix :tangle default.nix
# song_columns_list_format = "(40)[39]{t} | (30)[39]{a} | (30)[39]{f} (25)[39]{b} (5)[39]{l}"; # clean
song_columns_list_format = "(40)[39]{t} (30)[39]{a} (25)[39]{b} (5)[39]{l}"; # alternatives dont work in column list
#nice : 38
#+end_src

**** song list
#+begin_src nix :tangle default.nix
song_list_format = "{$5%t} | {$6%f$9} $r %p %b      {$4%a$1$9}$9";
#+end_src

**** current item
#+begin_src nix :tangle default.nix
current_item_prefix = "$(142)$r"; # highlight current
#+end_src

**** current item-inactive
#+begin_src nix :tangle default.nix
current_item_inactive_column_prefix = "$(24)$r"; #nice purp
#+end_src

*** docs
**** song format

#+begin_src
%l - length
%f - filename
%F - full filepath
%D - directory
%a - artist
%A - album artist
%t - title
%b - album
%y - date
%n - track number (01/12 -> 01)
%N - full track info (01/12 -> 01/12)
%g - genre
%c - composer
%p - performer
%d - disc
%C - comment
%P - priority
$R - begin right alignment
#+end_src

You can also put them in ={ }= and then they will be displayed only if all requested values are available and/or define alternate value with ={ }|{ }= e.g.

={%a - %t}|{%f}= will check if artist and title tags are available and if they are, display them. Otherwise it'll display filename.

Note: If you want to set limit on maximal length of a tag, just put the appropriate number between % and character that defines tag type, e.g. to make album take max. 20 terminal cells, use =%20b=.

Note: Format that is similar to "%a - %t" (i.e. without any additional braces) is equal to "{%a - %t}", so if one of the tags is missing, you'll get nothing.

Available values for colors:
- 0 - default window color (discards all other colors)
- 1 - black
- 2 - red
- 3 - green
- 4 - yellow
- 5 - blue
- 6 - magenta
- 7 - cyan
- 8 - white
- 9 - end of current color

Note: colors can be nested, so if you write $2some$5text$9, it'll disable only usage of blue color and make red the current one.

source:[[https://www.mankier.com/1/ncmpcpp#Bindings]]

*** alternative header
#+begin_src nix :tangle default.nix
alternative_header_first_line_format = "$0$aqqu$/a$9  {$6%a$9     }{$5%t$9}|{$3%f$9}  $0$atqq$/a$9";
alternative_header_second_line_format = "{{$7%b$9}}|{$4%d$9}";
alternative_ui_separator_color = 1;
#+end_src

*** window border color, activw window border
#+begin_src nix :tangle default.nix
window_border_color = 212; #pop up windows
active_window_border = 21;
#+end_src

*** state line
state flags color mpc status flags eg [rzxu]

#+begin_src nix :tangle default.nix
state_line_color = 1;
state_flags_color = 4; # mpc status flags eg rzxu
#+end_src

*** main window
#+begin_src nix :tangle default.nix
main_window_color = 69;
#+end_src

*** player state - play/pause
#+begin_src nix :tangle default.nix
player_state_color = 31; # playing/paused status
#+end_src

*** status bar
#+begin_src nix :tangle default.nix
statusbar_time_color = 87;
statusbar_color = 227; # song name on status bar

statusbar_visibility = true;
#+end_src

*** remaining time
#+begin_src nix :tangle default.nix
display_remaining_time = false; #instead of elapsed in status bar
#+end_src

*** volume
#+begin_src nix :tangle default.nix
volume_color = 124;
display_volume_level = true;
volume_change_step = 2;
#+end_src

*** progress bar
#+begin_src nix :tangle default.nix
progressbar_color = 24;
progressbar_look = "─⊙┄";
#progressbar_look = "─░─";
progressbar_elapsed_color = 74;
#progressbar_elapsed_color = 24; # muted
#+end_src

*** enable colors
#+begin_src nix :tangle default.nix
colors_enabled = true;
#+end_src

** playlists
ncmpc_like_songs_adding = true; # If enabled, pressing space on item, which is already in playlist will remove it, otherwise add it again.
#+begin_src nix :tangle default.nix
playlist_disable_highlight_delay = 5; #0 to disable fade
playlist_show_remaining_time = true; #header time remaining
playlist_shorten_total_times = true;
playlist_separate_albums = false; # add separator lines between albums in playlist view
ask_before_clearing_playlists = true;
#+end_src

** display mode , columns
#+begin_src nix :tangle default.nix
search_engine_display_mode = "columns";
browser_display_mode = "columns";
playlist_display_mode = "columns";
playlist_editor_display_mode = "columns";
browser_playlist_prefix = " - ";
#clock_display_seconds = yes
#+end_src

** mouse
+ mouse_list_scroll_whole_page = yes/no
        If enabled, mouse wheel will scroll the whole page of item list at a time, otherwise the number of lines specified by lines_scrolled variable.

#+begin_src nix :tangle default.nix
lines_scrolled = 8;
mouse_list_scroll_whole_page = true;
mouse_support = true;
#+end_src

** visualizer
+ visualizer_fifo_path = PATH
        Path to mpd fifo output. This is needed to make music visualizer work (note that output sound format of this fifo has to be either 44100:16:1 or 44100:16:2, depending on whether you want mono or stereo visualization)
+ visualizer_in_stereo = yes/no
        Should be set to 'yes', if fifo output's format was set to 44100:16:2.
#+begin_src nix :tangle default.nix
visualizer_output_name = "Visualizer feed";
visualizer_type = "wave_filled"; # wave, wave_filled, spectrum, ellipse
visualizer_in_stereo = "yes"; # yes if fifo set to 44100:16:2
visualizer_autoscale = true;
visualizer_spectrum_smooth_look = true;
# visualizer_color = "25, 38, 10";
visualizer_color = "25, 38, 104";
visualizer_look = "+|";
# visualizer_look = "●▮";
#+end_src

** ncmpcpp directory
+ ncmpcpp_directory = PATH
        Directory for storing ncmpcpp related files. Changing it is useful if you want to store everything somewhere else and provide command line setting for alternative location to config file which defines that while launching ncmpcpp.
#+begin_src nix :tangle default.nix
ncmpcpp_directory = "~/.local/share/ncmpcpp";
#+end_src

** mpd settings
+ mpd_communicat[[id:a34c5d79-9efd-40a7-a99a-87d96af60a1d][School]]ion_mode = MODE
        If set to 'polling', ncmpcpp will constantly poll mpd for its status. If set to 'notifications', ncmppcp will make use of 'idle' command and wait for events. This is more efficient and responsive, but may cause some trouble with <mpd-0.15, so if you run such version and encounter strange bugs (e.g. current track time not being updated), you will either have to use 'polling' or upgrade your mpd.
+ mpd_host = HOST
        Connect to MPD running on specified host/unix socket. When HOST starts with a '/', it is assumed to be a unix socket.
+ mpd_music_dir = PATH
        Search for files in specified directory. This is needed for ~tag editor~ to work.
       
# mpd_communication_mode = "notifications";
not working

#+begin_src nix :tangle default.nix
mpd_crossfade_time = 4;
mpd_connection_timeout = 5;
# mpd_host = "localhost";
mpd_host = "localhost";
mpd_port = 6600;
#+end_src

** on song change
#+begin_src nix :tangle default.nix
# execute_on_song_change = "~/.darth/scripts/player/songinfo.sh";
execute_on_song_change = "songart";
#execute_on_player_state_change = "";
#+end_src

** selected prefix tracks
#+begin_src nix :tangle default.nix
## Selected tracks ##
# selected_item_prefix = "->>";
# selected_item_prefix = "|>";
selected_item_prefix = "+  ";
discard_colors_if_item_is_selected = true;
#+end_src

** encoding
#+begin_src nix :tangle default.nix
system_encoding = "utf8";
regular_expressions =  "extended"; # none/basic/extended/perl;
generate_win32_compatible_filenames = true; # generated file names eg. with tag editor wont have  \?*:|
#+end_src

** delete files and directories
# allow_physical_directories_deletion = true; not working???

#+begin_src nix :tangle default.nix
allow_for_physical_item_deletion = true;
show_hidden_files_in_local_browser = false;
#startup_slave_screen = "browser";
#+end_src

* end
#+begin_src nix :tangle default.nix
};
 };
  }
#+end_src
